# Spec Reference: 192_embedding_mesh_foundation
import pytest
from pathlib import Path
from layers.l2_brain.structural_hardening.contracts import StructuralClass, RiskLevel, Recommendation
from layers.l2_brain.structural_hardening.evidence import EvidenceCollector
from layers.l2_brain.structural_hardening.classifier import StructuralClassifier


@pytest.fixture
def classifier(tmp_path):
    # Setup temporary directory mirroring repo structures
    repo_root = tmp_path
    
    # Create specs
    specs_dir = repo_root / "doc" / "specs"
    specs_dir.mkdir(parents=True)
    spec_file = specs_dir / "101_model_router.md"
    spec_file.write_text("spec_id: 101\n# Spec Reference: 101_model_router\nlayers/l2_brain/model_router.py")
    
    # Create active layers
    layers_dir = repo_root / "layers" / "l2_brain"
    layers_dir.mkdir(parents=True)
    
    # Init file (packaging glue)
    init_file = layers_dir / "__init__.py"
    init_file.touch()
    
    # Active runtime file
    runtime_file = layers_dir / "model_router.py"
    runtime_file.touch()
    
    # Generated file
    gen_file = layers_dir / "model_pb2.py"
    gen_file.write_text("# autogenerated pb2 code\nCode generated by protocol buffer compiler.")
    
    # Config file
    config_file = repo_root / "pyproject.toml"
    config_file.touch()
    
    # Legacy file
    legacy_dir = repo_root / "layers" / "l2_brain" / ".deprecated"
    legacy_dir.mkdir(parents=True)
    legacy_file = legacy_dir / "old_module.py"
    legacy_file.touch()
    
    # Report file
    report_dir = repo_root / ".aiwg" / "reports"
    report_dir.mkdir(parents=True)
    report_file = report_dir / "semantic_hardening_matrix_latest.json"
    report_file.touch()
    
    collector = EvidenceCollector(str(repo_root))
    return StructuralClassifier(collector)


def test_init_packaging_glue_classification(classifier):
    finding = classifier.classify({"path": "layers/l2_brain/__init__.py", "classification": "UNKNOWN"})
    assert finding.proposed_class == StructuralClass.ACTIVE_RUNTIME
    assert finding.risk == RiskLevel.LOW
    assert finding.recommendation == Recommendation.NO_ACTION
    assert any("__init__.py" in r for r in finding.reasons)


def test_active_spec_classification(classifier):
    finding = classifier.classify({"path": "doc/specs/101_model_router.md", "classification": "SPEC"})
    assert finding.proposed_class == StructuralClass.ACTIVE_SPEC
    assert finding.risk == RiskLevel.LOW
    assert finding.recommendation == Recommendation.KEEP_AND_TEST


def test_generated_file_classification(classifier):
    finding = classifier.classify({"path": "layers/l2_brain/model_pb2.py", "classification": "GENERATED"})
    assert finding.proposed_class == StructuralClass.GENERATED
    assert finding.risk == RiskLevel.LOW
    assert finding.recommendation == Recommendation.MARK_GENERATED


def test_config_file_classification(classifier):
    finding = classifier.classify({"path": "pyproject.toml", "classification": "CONFIG"})
    assert finding.proposed_class == StructuralClass.CONFIG
    assert finding.risk == RiskLevel.LOW


def test_legacy_file_classification(classifier):
    finding = classifier.classify({"path": "layers/l2_brain/.deprecated/old_module.py", "classification": "LEGACY"})
    assert finding.proposed_class == StructuralClass.LEGACY
    assert finding.risk == RiskLevel.LOW
    assert finding.recommendation == Recommendation.MARK_LEGACY


def test_report_file_classification(classifier):
    finding = classifier.classify({"path": ".aiwg/reports/semantic_hardening_matrix_latest.json", "classification": "REPORT"})
    assert finding.proposed_class == StructuralClass.REPORT
    assert finding.risk == RiskLevel.LOW


def test_active_runtime_with_spec_classification(classifier):
    finding = classifier.classify({"path": "layers/l2_brain/model_router.py", "classification": "UNKNOWN"})
    # Since it has a spec referencing it (indexed during setup), it is classified as ACTIVE_RUNTIME
    assert finding.proposed_class == StructuralClass.ACTIVE_RUNTIME
    assert finding.risk == RiskLevel.MEDIUM
    assert finding.recommendation == Recommendation.MAP_TO_TEST
