# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/dummie/v2/memory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/dummie/v2/memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from proto.dummie.v2 import core_pb2 as proto_dot_dummie_dot_v2_dot_core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%proto/dummie/v2/memory.proto\x12\x12\x61gent_orquestor.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#proto/dummie/v2/core.proto\"\xd7\x01\n\x13\x41mbiguityResolution\x12\x0c\n\x04tick\x18\x01 \x01(\x04\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\x12\r\n\x05topic\x18\x04 \x01(\t\x12\x12\n\nuser_input\x18\x05 \x01(\t\x12\x17\n\x0fresolution_path\x18\x06 \x01(\t\x12\x35\n\x10\x61ssociated_event\x18\x07 \x01(\x0b\x32\x1b.dummie.v2.EventId\"\xbf\x01\n\rLessonLearned\x12\x0c\n\x04tick\x18\x01 \x01(\x04\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x61iled_pattern\x18\x03 \x01(\t\x12\x17\n\x0fsuccess_pattern\x18\x04 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x05 \x01(\x02\x12\x0c\n\x04tags\x18\x06 \x03(\t\x12\x35\n\x10\x61ssociated_event\x18\x07 \x01(\x0b\x32\x1b.dummie.v2.EventId\"\xc1\x01\n\x15\x41rchitecturalDecision\x12\x0c\n\x04tick\x18\x01 \x01(\x04\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65\x63ision\x18\x03 \x01(\t\x12\x11\n\trationale\x18\x04 \x01(\t\x12\x15\n\rspec_involved\x18\x05 \x01(\t\x12\x15\n\rimpact_radius\x18\x06 \x03(\t\x12\x35\n\x10\x61ssociated_event\x18\x07 \x01(\x0b\x32\x1b.dummie.v2.EventId\"\xd3\x01\n\rSessionMemory\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12<\n\x0b\x61mbiguities\x18\x02 \x03(\x0b\x32\'.dummie.v2.AmbiguityResolution\x12\x32\n\x07lessons\x18\x03 \x03(\x0b\x32!.dummie.v2.LessonLearned\x12<\n\tdecisions\x18\x04 \x03(\x0b\x32).dummie.v2.ArchitecturalDecisionB7Z5io.dummie.v2/nervous/proto;dummie_v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.dummie.v2.memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5io.dummie.v2/nervous/proto;dummie_v2'
  _globals['_AMBIGUITYRESOLUTION']._serialized_start=132
  _globals['_AMBIGUITYRESOLUTION']._serialized_end=347
  _globals['_LESSONLEARNED']._serialized_start=350
  _globals['_LESSONLEARNED']._serialized_end=541
  _globals['_ARCHITECTURALDECISION']._serialized_start=544
  _globals['_ARCHITECTURALDECISION']._serialized_end=737
  _globals['_SESSIONMEMORY']._serialized_start=740
  _globals['_SESSIONMEMORY']._serialized_end=951
# @@protoc_insertion_point(module_scope)
