// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/dummie/v2/core.proto

package dummie_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// === Nivel de Autoridad (Spec 10/12/18) ===
type AuthorityLevel int32

const (
	AuthorityLevel_AUTHORITY_UNSPECIFIED AuthorityLevel = 0
	AuthorityLevel_AGENT                 AuthorityLevel = 1 // Operación de rutina
	AuthorityLevel_ENGINEER              AuthorityLevel = 2 // Refactor de capas bajas (L1-L4)
	AuthorityLevel_ARCHITECT             AuthorityLevel = 3 // Mutación topológica
	AuthorityLevel_OVERSEER              AuthorityLevel = 4 // L0 - Sistema base
	AuthorityLevel_HUMAN                 AuthorityLevel = 5 // PAH (Override absoluto)
)

// Enum value maps for AuthorityLevel.
var (
	AuthorityLevel_name = map[int32]string{
		0: "AUTHORITY_UNSPECIFIED",
		1: "AGENT",
		2: "ENGINEER",
		3: "ARCHITECT",
		4: "OVERSEER",
		5: "HUMAN",
	}
	AuthorityLevel_value = map[string]int32{
		"AUTHORITY_UNSPECIFIED": 0,
		"AGENT":                 1,
		"ENGINEER":              2,
		"ARCHITECT":             3,
		"OVERSEER":              4,
		"HUMAN":                 5,
	}
)

func (x AuthorityLevel) Enum() *AuthorityLevel {
	p := new(AuthorityLevel)
	*p = x
	return p
}

func (x AuthorityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dummie_v2_core_proto_enumTypes[0].Descriptor()
}

func (AuthorityLevel) Type() protoreflect.EnumType {
	return &file_proto_dummie_v2_core_proto_enumTypes[0]
}

func (x AuthorityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorityLevel.Descriptor instead.
func (AuthorityLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_dummie_v2_core_proto_rawDescGZIP(), []int{0}
}

type DeathReason int32

const (
	DeathReason_UNKNOWN          DeathReason = 0
	DeathReason_SEMANTIC_TIMEOUT DeathReason = 1
	DeathReason_RESOURCES_OOM    DeathReason = 2
	DeathReason_INFINITE_LOOP    DeathReason = 3
	DeathReason_VRAM_LIMIT       DeathReason = 4
	DeathReason_SHIELD_VETO      DeathReason = 5
)

// Enum value maps for DeathReason.
var (
	DeathReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "SEMANTIC_TIMEOUT",
		2: "RESOURCES_OOM",
		3: "INFINITE_LOOP",
		4: "VRAM_LIMIT",
		5: "SHIELD_VETO",
	}
	DeathReason_value = map[string]int32{
		"UNKNOWN":          0,
		"SEMANTIC_TIMEOUT": 1,
		"RESOURCES_OOM":    2,
		"INFINITE_LOOP":    3,
		"VRAM_LIMIT":       4,
		"SHIELD_VETO":      5,
	}
)

func (x DeathReason) Enum() *DeathReason {
	p := new(DeathReason)
	*p = x
	return p
}

func (x DeathReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeathReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dummie_v2_core_proto_enumTypes[1].Descriptor()
}

func (DeathReason) Type() protoreflect.EnumType {
	return &file_proto_dummie_v2_core_proto_enumTypes[1]
}

func (x DeathReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeathReason.Descriptor instead.
func (DeathReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_dummie_v2_core_proto_rawDescGZIP(), []int{1}
}

// === Identidad Causal 4D-TES (Spec 10) ===
type EventId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniverseId    string                 `protobuf:"bytes,1,opt,name=universe_id,json=universeId,proto3" json:"universe_id,omitempty"`     // ID del Proyecto (Wing)
	BranchId      string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`           // ID de la Rama de Razonamiento
	LamportTick   uint64                 `protobuf:"varint,3,opt,name=lamport_tick,json=lamportTick,proto3" json:"lamport_tick,omitempty"` // Reloj de Lamport
	Authority     AuthorityLevel         `protobuf:"varint,4,opt,name=authority,proto3,enum=dummie.v2.AuthorityLevel" json:"authority,omitempty"`
	EntropyCount  uint32                 `protobuf:"varint,5,opt,name=entropy_count,json=entropyCount,proto3" json:"entropy_count,omitempty"` // Contador de reintentos/muertes
	IsToxic       bool                   `protobuf:"varint,6,opt,name=is_toxic,json=isToxic,proto3" json:"is_toxic,omitempty"`                // Flag de limpieza de VRAM
	NecrosisInfo  *DeathMetadata         `protobuf:"bytes,7,opt,name=necrosis_info,json=necrosisInfo,proto3" json:"necrosis_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventId) Reset() {
	*x = EventId{}
	mi := &file_proto_dummie_v2_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventId) ProtoMessage() {}

func (x *EventId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventId.ProtoReflect.Descriptor instead.
func (*EventId) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_core_proto_rawDescGZIP(), []int{0}
}

func (x *EventId) GetUniverseId() string {
	if x != nil {
		return x.UniverseId
	}
	return ""
}

func (x *EventId) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *EventId) GetLamportTick() uint64 {
	if x != nil {
		return x.LamportTick
	}
	return 0
}

func (x *EventId) GetAuthority() AuthorityLevel {
	if x != nil {
		return x.Authority
	}
	return AuthorityLevel_AUTHORITY_UNSPECIFIED
}

func (x *EventId) GetEntropyCount() uint32 {
	if x != nil {
		return x.EntropyCount
	}
	return 0
}

func (x *EventId) GetIsToxic() bool {
	if x != nil {
		return x.IsToxic
	}
	return false
}

func (x *EventId) GetNecrosisInfo() *DeathMetadata {
	if x != nil {
		return x.NecrosisInfo
	}
	return nil
}

type DeathMetadata struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Reason               DeathReason            `protobuf:"varint,1,opt,name=reason,proto3,enum=dummie.v2.DeathReason" json:"reason,omitempty"`
	LastKnownInstruction string                 `protobuf:"bytes,2,opt,name=last_known_instruction,json=lastKnownInstruction,proto3" json:"last_known_instruction,omitempty"`
	SupervisorNote       string                 `protobuf:"bytes,3,opt,name=supervisor_note,json=supervisorNote,proto3" json:"supervisor_note,omitempty"`
	StackTrace           string                 `protobuf:"bytes,4,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeathMetadata) Reset() {
	*x = DeathMetadata{}
	mi := &file_proto_dummie_v2_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeathMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeathMetadata) ProtoMessage() {}

func (x *DeathMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeathMetadata.ProtoReflect.Descriptor instead.
func (*DeathMetadata) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_core_proto_rawDescGZIP(), []int{1}
}

func (x *DeathMetadata) GetReason() DeathReason {
	if x != nil {
		return x.Reason
	}
	return DeathReason_UNKNOWN
}

func (x *DeathMetadata) GetLastKnownInstruction() string {
	if x != nil {
		return x.LastKnownInstruction
	}
	return ""
}

func (x *DeathMetadata) GetSupervisorNote() string {
	if x != nil {
		return x.SupervisorNote
	}
	return ""
}

func (x *DeathMetadata) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

// === Descriptor de Memoria Compartida (MemoryTicket - Spec 10/16) ===
// Este mensaje es el descriptor que viaja por el Control Plane (NATS).
// El buffer real en SHM comienza con la cabecera binaria de 64B definida en Spec 16.
type MemoryTicket struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ShmPath   string                 `protobuf:"bytes,1,opt,name=shm_path,json=shmPath,proto3" json:"shm_path,omitempty"` // Ruta al archivo mmap o ID de SHM
	Offset    uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                 // Offset al inicio del RecordBatch (tras los 64B de header)
	Length    uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`                 // Longitud del RecordBatch
	Alignment uint32                 `protobuf:"varint,4,opt,name=alignment,proto3" json:"alignment,omitempty"`           // Alineación (Default: 64)
	// RBAC Topográfico (Spec 18)
	RequiredLevel  AuthorityLevel `protobuf:"varint,5,opt,name=required_level,json=requiredLevel,proto3,enum=dummie.v2.AuthorityLevel" json:"required_level,omitempty"`
	NamespaceScope string         `protobuf:"bytes,6,opt,name=namespace_scope,json=namespaceScope,proto3" json:"namespace_scope,omitempty"`
	IsToxic        bool           `protobuf:"varint,7,opt,name=is_toxic,json=isToxic,proto3" json:"is_toxic,omitempty"`
	TicketUuidHigh uint64         `protobuf:"varint,8,opt,name=ticket_uuid_high,json=ticketUuidHigh,proto3" json:"ticket_uuid_high,omitempty"` // UUID v4 (High 64 bits)
	TicketUuidLow  uint64         `protobuf:"varint,9,opt,name=ticket_uuid_low,json=ticketUuidLow,proto3" json:"ticket_uuid_low,omitempty"`    // UUID v4 (Low 64 bits)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryTicket) Reset() {
	*x = MemoryTicket{}
	mi := &file_proto_dummie_v2_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryTicket) ProtoMessage() {}

func (x *MemoryTicket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryTicket.ProtoReflect.Descriptor instead.
func (*MemoryTicket) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_core_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryTicket) GetShmPath() string {
	if x != nil {
		return x.ShmPath
	}
	return ""
}

func (x *MemoryTicket) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MemoryTicket) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *MemoryTicket) GetAlignment() uint32 {
	if x != nil {
		return x.Alignment
	}
	return 0
}

func (x *MemoryTicket) GetRequiredLevel() AuthorityLevel {
	if x != nil {
		return x.RequiredLevel
	}
	return AuthorityLevel_AUTHORITY_UNSPECIFIED
}

func (x *MemoryTicket) GetNamespaceScope() string {
	if x != nil {
		return x.NamespaceScope
	}
	return ""
}

func (x *MemoryTicket) GetIsToxic() bool {
	if x != nil {
		return x.IsToxic
	}
	return false
}

func (x *MemoryTicket) GetTicketUuidHigh() uint64 {
	if x != nil {
		return x.TicketUuidHigh
	}
	return 0
}

func (x *MemoryTicket) GetTicketUuidLow() uint64 {
	if x != nil {
		return x.TicketUuidLow
	}
	return 0
}

// === Protocolo de Migración Phase-Gate (Spec 10) ===
type PhaseTransitionSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPhase     string                 `protobuf:"bytes,1,opt,name=from_phase,json=fromPhase,proto3" json:"from_phase,omitempty"`
	ToPhase       string                 `protobuf:"bytes,2,opt,name=to_phase,json=toPhase,proto3" json:"to_phase,omitempty"`
	CatToken      string                 `protobuf:"bytes,3,opt,name=cat_token,json=catToken,proto3" json:"cat_token,omitempty"` // Token de validación (CAT)
	LamportTick   uint64                 `protobuf:"varint,4,opt,name=lamport_tick,json=lamportTick,proto3" json:"lamport_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseTransitionSignal) Reset() {
	*x = PhaseTransitionSignal{}
	mi := &file_proto_dummie_v2_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseTransitionSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseTransitionSignal) ProtoMessage() {}

func (x *PhaseTransitionSignal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseTransitionSignal.ProtoReflect.Descriptor instead.
func (*PhaseTransitionSignal) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_core_proto_rawDescGZIP(), []int{3}
}

func (x *PhaseTransitionSignal) GetFromPhase() string {
	if x != nil {
		return x.FromPhase
	}
	return ""
}

func (x *PhaseTransitionSignal) GetToPhase() string {
	if x != nil {
		return x.ToPhase
	}
	return ""
}

func (x *PhaseTransitionSignal) GetCatToken() string {
	if x != nil {
		return x.CatToken
	}
	return ""
}

func (x *PhaseTransitionSignal) GetLamportTick() uint64 {
	if x != nil {
		return x.LamportTick
	}
	return 0
}

type PhaseTransitionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	StatusReport  string                 `protobuf:"bytes,3,opt,name=status_report,json=statusReport,proto3" json:"status_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseTransitionAck) Reset() {
	*x = PhaseTransitionAck{}
	mi := &file_proto_dummie_v2_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseTransitionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseTransitionAck) ProtoMessage() {}

func (x *PhaseTransitionAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseTransitionAck.ProtoReflect.Descriptor instead.
func (*PhaseTransitionAck) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_core_proto_rawDescGZIP(), []int{4}
}

func (x *PhaseTransitionAck) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *PhaseTransitionAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PhaseTransitionAck) GetStatusReport() string {
	if x != nil {
		return x.StatusReport
	}
	return ""
}

// === Errores Políglotas (Spec 10) ===
type PolyglotError struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StackTrace      string                 `protobuf:"bytes,3,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	OriginLayer     string                 `protobuf:"bytes,4,opt,name=origin_layer,json=originLayer,proto3" json:"origin_layer,omitempty"` // L0..L6
	IsRecoverable   bool                   `protobuf:"varint,5,opt,name=is_recoverable,json=isRecoverable,proto3" json:"is_recoverable,omitempty"`
	AssociatedEvent *EventId               `protobuf:"bytes,6,opt,name=associated_event,json=associatedEvent,proto3" json:"associated_event,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolyglotError) Reset() {
	*x = PolyglotError{}
	mi := &file_proto_dummie_v2_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolyglotError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolyglotError) ProtoMessage() {}

func (x *PolyglotError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolyglotError.ProtoReflect.Descriptor instead.
func (*PolyglotError) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_core_proto_rawDescGZIP(), []int{5}
}

func (x *PolyglotError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PolyglotError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PolyglotError) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *PolyglotError) GetOriginLayer() string {
	if x != nil {
		return x.OriginLayer
	}
	return ""
}

func (x *PolyglotError) GetIsRecoverable() bool {
	if x != nil {
		return x.IsRecoverable
	}
	return false
}

func (x *PolyglotError) GetAssociatedEvent() *EventId {
	if x != nil {
		return x.AssociatedEvent
	}
	return nil
}

var File_proto_dummie_v2_core_proto protoreflect.FileDescriptor

const file_proto_dummie_v2_core_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/dummie/v2/core.proto\x12\tdummie.v2\"\xa2\x02\n" +
	"\aEventId\x12\x1f\n" +
	"\vuniverse_id\x18\x01 \x01(\tR\n" +
	"universeId\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\x12!\n" +
	"\flamport_tick\x18\x03 \x01(\x04R\vlamportTick\x127\n" +
	"\tauthority\x18\x04 \x01(\x0e2\x19.dummie.v2.AuthorityLevelR\tauthority\x12#\n" +
	"\rentropy_count\x18\x05 \x01(\rR\fentropyCount\x12\x19\n" +
	"\bis_toxic\x18\x06 \x01(\bR\aisToxic\x12=\n" +
	"\rnecrosis_info\x18\a \x01(\v2\x18.dummie.v2.DeathMetadataR\fnecrosisInfo\"\xbf\x01\n" +
	"\rDeathMetadata\x12.\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x16.dummie.v2.DeathReasonR\x06reason\x124\n" +
	"\x16last_known_instruction\x18\x02 \x01(\tR\x14lastKnownInstruction\x12'\n" +
	"\x0fsupervisor_note\x18\x03 \x01(\tR\x0esupervisorNote\x12\x1f\n" +
	"\vstack_trace\x18\x04 \x01(\tR\n" +
	"stackTrace\"\xcf\x02\n" +
	"\fMemoryTicket\x12\x19\n" +
	"\bshm_path\x18\x01 \x01(\tR\ashmPath\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\x12\x1c\n" +
	"\talignment\x18\x04 \x01(\rR\talignment\x12@\n" +
	"\x0erequired_level\x18\x05 \x01(\x0e2\x19.dummie.v2.AuthorityLevelR\rrequiredLevel\x12'\n" +
	"\x0fnamespace_scope\x18\x06 \x01(\tR\x0enamespaceScope\x12\x19\n" +
	"\bis_toxic\x18\a \x01(\bR\aisToxic\x12(\n" +
	"\x10ticket_uuid_high\x18\b \x01(\x04R\x0eticketUuidHigh\x12&\n" +
	"\x0fticket_uuid_low\x18\t \x01(\x04R\rticketUuidLow\"\x91\x01\n" +
	"\x15PhaseTransitionSignal\x12\x1d\n" +
	"\n" +
	"from_phase\x18\x01 \x01(\tR\tfromPhase\x12\x19\n" +
	"\bto_phase\x18\x02 \x01(\tR\atoPhase\x12\x1b\n" +
	"\tcat_token\x18\x03 \x01(\tR\bcatToken\x12!\n" +
	"\flamport_tick\x18\x04 \x01(\x04R\vlamportTick\"h\n" +
	"\x12PhaseTransitionAck\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12#\n" +
	"\rstatus_report\x18\x03 \x01(\tR\fstatusReport\"\xe7\x01\n" +
	"\rPolyglotError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x01(\tR\n" +
	"stackTrace\x12!\n" +
	"\forigin_layer\x18\x04 \x01(\tR\voriginLayer\x12%\n" +
	"\x0eis_recoverable\x18\x05 \x01(\bR\risRecoverable\x12=\n" +
	"\x10associated_event\x18\x06 \x01(\v2\x12.dummie.v2.EventIdR\x0fassociatedEvent*l\n" +
	"\x0eAuthorityLevel\x12\x19\n" +
	"\x15AUTHORITY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05AGENT\x10\x01\x12\f\n" +
	"\bENGINEER\x10\x02\x12\r\n" +
	"\tARCHITECT\x10\x03\x12\f\n" +
	"\bOVERSEER\x10\x04\x12\t\n" +
	"\x05HUMAN\x10\x05*w\n" +
	"\vDeathReason\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x14\n" +
	"\x10SEMANTIC_TIMEOUT\x10\x01\x12\x11\n" +
	"\rRESOURCES_OOM\x10\x02\x12\x11\n" +
	"\rINFINITE_LOOP\x10\x03\x12\x0e\n" +
	"\n" +
	"VRAM_LIMIT\x10\x04\x12\x0f\n" +
	"\vSHIELD_VETO\x10\x05B&Z$io.dummie.v2/nervous/proto;dummie_v2b\x06proto3"

var (
	file_proto_dummie_v2_core_proto_rawDescOnce sync.Once
	file_proto_dummie_v2_core_proto_rawDescData []byte
)

func file_proto_dummie_v2_core_proto_rawDescGZIP() []byte {
	file_proto_dummie_v2_core_proto_rawDescOnce.Do(func() {
		file_proto_dummie_v2_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dummie_v2_core_proto_rawDesc), len(file_proto_dummie_v2_core_proto_rawDesc)))
	})
	return file_proto_dummie_v2_core_proto_rawDescData
}

var file_proto_dummie_v2_core_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_dummie_v2_core_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_dummie_v2_core_proto_goTypes = []any{
	(AuthorityLevel)(0),           // 0: dummie.v2.AuthorityLevel
	(DeathReason)(0),              // 1: dummie.v2.DeathReason
	(*EventId)(nil),               // 2: dummie.v2.EventId
	(*DeathMetadata)(nil),         // 3: dummie.v2.DeathMetadata
	(*MemoryTicket)(nil),          // 4: dummie.v2.MemoryTicket
	(*PhaseTransitionSignal)(nil), // 5: dummie.v2.PhaseTransitionSignal
	(*PhaseTransitionAck)(nil),    // 6: dummie.v2.PhaseTransitionAck
	(*PolyglotError)(nil),         // 7: dummie.v2.PolyglotError
}
var file_proto_dummie_v2_core_proto_depIdxs = []int32{
	0, // 0: dummie.v2.EventId.authority:type_name -> dummie.v2.AuthorityLevel
	3, // 1: dummie.v2.EventId.necrosis_info:type_name -> dummie.v2.DeathMetadata
	1, // 2: dummie.v2.DeathMetadata.reason:type_name -> dummie.v2.DeathReason
	0, // 3: dummie.v2.MemoryTicket.required_level:type_name -> dummie.v2.AuthorityLevel
	2, // 4: dummie.v2.PolyglotError.associated_event:type_name -> dummie.v2.EventId
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_dummie_v2_core_proto_init() }
func file_proto_dummie_v2_core_proto_init() {
	if File_proto_dummie_v2_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dummie_v2_core_proto_rawDesc), len(file_proto_dummie_v2_core_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dummie_v2_core_proto_goTypes,
		DependencyIndexes: file_proto_dummie_v2_core_proto_depIdxs,
		EnumInfos:         file_proto_dummie_v2_core_proto_enumTypes,
		MessageInfos:      file_proto_dummie_v2_core_proto_msgTypes,
	}.Build()
	File_proto_dummie_v2_core_proto = out.File
	file_proto_dummie_v2_core_proto_goTypes = nil
	file_proto_dummie_v2_core_proto_depIdxs = nil
}
