// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/dummie/v2/memory.proto

package dummie_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// === Registro de Resoluciones de Ambigüedad (Spec 34/36) ===
type AmbiguityResolution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tick            uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"` // Lamport Clock
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AgentId         string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Namespace del agente
	Topic           string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	UserInput       string                 `protobuf:"bytes,5,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`
	ResolutionPath  string                 `protobuf:"bytes,6,opt,name=resolution_path,json=resolutionPath,proto3" json:"resolution_path,omitempty"`
	AssociatedEvent *EventId               `protobuf:"bytes,7,opt,name=associated_event,json=associatedEvent,proto3" json:"associated_event,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AmbiguityResolution) Reset() {
	*x = AmbiguityResolution{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmbiguityResolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmbiguityResolution) ProtoMessage() {}

func (x *AmbiguityResolution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmbiguityResolution.ProtoReflect.Descriptor instead.
func (*AmbiguityResolution) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{0}
}

func (x *AmbiguityResolution) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *AmbiguityResolution) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AmbiguityResolution) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AmbiguityResolution) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AmbiguityResolution) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *AmbiguityResolution) GetResolutionPath() string {
	if x != nil {
		return x.ResolutionPath
	}
	return ""
}

func (x *AmbiguityResolution) GetAssociatedEvent() *EventId {
	if x != nil {
		return x.AssociatedEvent
	}
	return nil
}

// === Registro de Lecciones Aprendidas (Spec 35/36) ===
type LessonLearned struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tick            uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	AgentId         string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	FailedPattern   string                 `protobuf:"bytes,3,opt,name=failed_pattern,json=failedPattern,proto3" json:"failed_pattern,omitempty"`
	SuccessPattern  string                 `protobuf:"bytes,4,opt,name=success_pattern,json=successPattern,proto3" json:"success_pattern,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Tags            []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	AssociatedEvent *EventId               `protobuf:"bytes,7,opt,name=associated_event,json=associatedEvent,proto3" json:"associated_event,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LessonLearned) Reset() {
	*x = LessonLearned{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonLearned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonLearned) ProtoMessage() {}

func (x *LessonLearned) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonLearned.ProtoReflect.Descriptor instead.
func (*LessonLearned) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{1}
}

func (x *LessonLearned) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *LessonLearned) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LessonLearned) GetFailedPattern() string {
	if x != nil {
		return x.FailedPattern
	}
	return ""
}

func (x *LessonLearned) GetSuccessPattern() string {
	if x != nil {
		return x.SuccessPattern
	}
	return ""
}

func (x *LessonLearned) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *LessonLearned) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LessonLearned) GetAssociatedEvent() *EventId {
	if x != nil {
		return x.AssociatedEvent
	}
	return nil
}

// === Registro de Decisiones Arquitectónicas (Ligeras) ===
type ArchitecturalDecision struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tick            uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	AgentId         string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Decision        string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Rationale       string                 `protobuf:"bytes,4,opt,name=rationale,proto3" json:"rationale,omitempty"`
	SpecInvolved    string                 `protobuf:"bytes,5,opt,name=spec_involved,json=specInvolved,proto3" json:"spec_involved,omitempty"`
	ImpactRadius    []string               `protobuf:"bytes,6,rep,name=impact_radius,json=impactRadius,proto3" json:"impact_radius,omitempty"`
	AssociatedEvent *EventId               `protobuf:"bytes,7,opt,name=associated_event,json=associatedEvent,proto3" json:"associated_event,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArchitecturalDecision) Reset() {
	*x = ArchitecturalDecision{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchitecturalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchitecturalDecision) ProtoMessage() {}

func (x *ArchitecturalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchitecturalDecision.ProtoReflect.Descriptor instead.
func (*ArchitecturalDecision) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{2}
}

func (x *ArchitecturalDecision) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *ArchitecturalDecision) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ArchitecturalDecision) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ArchitecturalDecision) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *ArchitecturalDecision) GetSpecInvolved() string {
	if x != nil {
		return x.SpecInvolved
	}
	return ""
}

func (x *ArchitecturalDecision) GetImpactRadius() []string {
	if x != nil {
		return x.ImpactRadius
	}
	return nil
}

func (x *ArchitecturalDecision) GetAssociatedEvent() *EventId {
	if x != nil {
		return x.AssociatedEvent
	}
	return nil
}

// === Contenedor de Memoria de Sesión ===
type SessionMemory struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	SessionId     string                   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Ambiguities   []*AmbiguityResolution   `protobuf:"bytes,2,rep,name=ambiguities,proto3" json:"ambiguities,omitempty"`
	Lessons       []*LessonLearned         `protobuf:"bytes,3,rep,name=lessons,proto3" json:"lessons,omitempty"`
	Decisions     []*ArchitecturalDecision `protobuf:"bytes,4,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMemory) Reset() {
	*x = SessionMemory{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMemory) ProtoMessage() {}

func (x *SessionMemory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMemory.ProtoReflect.Descriptor instead.
func (*SessionMemory) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{3}
}

func (x *SessionMemory) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionMemory) GetAmbiguities() []*AmbiguityResolution {
	if x != nil {
		return x.Ambiguities
	}
	return nil
}

func (x *SessionMemory) GetLessons() []*LessonLearned {
	if x != nil {
		return x.Lessons
	}
	return nil
}

func (x *SessionMemory) GetDecisions() []*ArchitecturalDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

var File_proto_dummie_v2_memory_proto protoreflect.FileDescriptor

const file_proto_dummie_v2_memory_proto_rawDesc = "" +
	"\n" +
	"%proto/dummie/v2/memory.proto\x12\x12dummie.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#proto/dummie/v2/core.proto\"\xa4\x02\n" +
	"\x13AmbiguityResolution\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12\x1d\n" +
	"\n" +
	"user_input\x18\x05 \x01(\tR\tuserInput\x12'\n" +
	"\x0fresolution_path\x18\x06 \x01(\tR\x0eresolutionPath\x12F\n" +
	"\x10associated_event\x18\a \x01(\v2\x1b.dummie.v2.EventIdR\x0fassociatedEvent\"\x95\x02\n" +
	"\rLessonLearned\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12%\n" +
	"\x0efailed_pattern\x18\x03 \x01(\tR\rfailedPattern\x12'\n" +
	"\x0fsuccess_pattern\x18\x04 \x01(\tR\x0esuccessPattern\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\x02R\x0fconfidenceScore\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12F\n" +
	"\x10associated_event\x18\a \x01(\v2\x1b.dummie.v2.EventIdR\x0fassociatedEvent\"\x92\x02\n" +
	"\x15ArchitecturalDecision\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12\x1c\n" +
	"\trationale\x18\x04 \x01(\tR\trationale\x12#\n" +
	"\rspec_involved\x18\x05 \x01(\tR\fspecInvolved\x12#\n" +
	"\rimpact_radius\x18\x06 \x03(\tR\fimpactRadius\x12F\n" +
	"\x10associated_event\x18\a \x01(\v2\x1b.dummie.v2.EventIdR\x0fassociatedEvent\"\xff\x01\n" +
	"\rSessionMemory\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12I\n" +
	"\vambiguities\x18\x02 \x03(\v2'.dummie.v2.AmbiguityResolutionR\vambiguities\x12;\n" +
	"\alessons\x18\x03 \x03(\v2!.dummie.v2.LessonLearnedR\alessons\x12G\n" +
	"\tdecisions\x18\x04 \x03(\v2).dummie.v2.ArchitecturalDecisionR\tdecisionsB7Z5io.dummie.v2/nervous/proto;dummie_v2b\x06proto3"

var (
	file_proto_dummie_v2_memory_proto_rawDescOnce sync.Once
	file_proto_dummie_v2_memory_proto_rawDescData []byte
)

func file_proto_dummie_v2_memory_proto_rawDescGZIP() []byte {
	file_proto_dummie_v2_memory_proto_rawDescOnce.Do(func() {
		file_proto_dummie_v2_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dummie_v2_memory_proto_rawDesc), len(file_proto_dummie_v2_memory_proto_rawDesc)))
	})
	return file_proto_dummie_v2_memory_proto_rawDescData
}

var file_proto_dummie_v2_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_dummie_v2_memory_proto_goTypes = []any{
	(*AmbiguityResolution)(nil),   // 0: dummie.v2.AmbiguityResolution
	(*LessonLearned)(nil),         // 1: dummie.v2.LessonLearned
	(*ArchitecturalDecision)(nil), // 2: dummie.v2.ArchitecturalDecision
	(*SessionMemory)(nil),         // 3: dummie.v2.SessionMemory
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*EventId)(nil),               // 5: dummie.v2.EventId
}
var file_proto_dummie_v2_memory_proto_depIdxs = []int32{
	4, // 0: dummie.v2.AmbiguityResolution.timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: dummie.v2.AmbiguityResolution.associated_event:type_name -> dummie.v2.EventId
	5, // 2: dummie.v2.LessonLearned.associated_event:type_name -> dummie.v2.EventId
	5, // 3: dummie.v2.ArchitecturalDecision.associated_event:type_name -> dummie.v2.EventId
	0, // 4: dummie.v2.SessionMemory.ambiguities:type_name -> dummie.v2.AmbiguityResolution
	1, // 5: dummie.v2.SessionMemory.lessons:type_name -> dummie.v2.LessonLearned
	2, // 6: dummie.v2.SessionMemory.decisions:type_name -> dummie.v2.ArchitecturalDecision
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_dummie_v2_memory_proto_init() }
func file_proto_dummie_v2_memory_proto_init() {
	if File_proto_dummie_v2_memory_proto != nil {
		return
	}
	file_proto_dummie_v2_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dummie_v2_memory_proto_rawDesc), len(file_proto_dummie_v2_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dummie_v2_memory_proto_goTypes,
		DependencyIndexes: file_proto_dummie_v2_memory_proto_depIdxs,
		MessageInfos:      file_proto_dummie_v2_memory_proto_msgTypes,
	}.Build()
	File_proto_dummie_v2_memory_proto = out.File
	file_proto_dummie_v2_memory_proto_goTypes = nil
	file_proto_dummie_v2_memory_proto_depIdxs = nil
}
