// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/dummie/v2/orchestration.proto

package dummie_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskResult_Status int32

const (
	TaskResult_SUCCESS    TaskResult_Status = 0
	TaskResult_FAILURE    TaskResult_Status = 1
	TaskResult_QUARANTINE TaskResult_Status = 2
)

// Enum value maps for TaskResult_Status.
var (
	TaskResult_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
		2: "QUARANTINE",
	}
	TaskResult_Status_value = map[string]int32{
		"SUCCESS":    0,
		"FAILURE":    1,
		"QUARANTINE": 2,
	}
)

func (x TaskResult_Status) Enum() *TaskResult_Status {
	p := new(TaskResult_Status)
	*p = x
	return p
}

func (x TaskResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dummie_v2_orchestration_proto_enumTypes[0].Descriptor()
}

func (TaskResult_Status) Type() protoreflect.EnumType {
	return &file_proto_dummie_v2_orchestration_proto_enumTypes[0]
}

func (x TaskResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResult_Status.Descriptor instead.
func (TaskResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{7, 0}
}

type SovereignContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PersonalityRef string                 `protobuf:"bytes,1,opt,name=personality_ref,json=personalityRef,proto3" json:"personality_ref,omitempty"` // e.g., "DE-V2-L0-33"
	LedgerLink     string                 `protobuf:"bytes,2,opt,name=ledger_link,json=ledgerLink,proto3" json:"ledger_link,omitempty"`             // e.g., "DE-V2-L2-34"
	ROIThreshold   float32                `protobuf:"fixed32,3,opt,name=ROI_threshold,json=ROIThreshold,proto3" json:"ROI_threshold,omitempty"`     // Umbral de decisión económica
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SovereignContext) Reset() {
	*x = SovereignContext{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SovereignContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SovereignContext) ProtoMessage() {}

func (x *SovereignContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SovereignContext.ProtoReflect.Descriptor instead.
func (*SovereignContext) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *SovereignContext) GetPersonalityRef() string {
	if x != nil {
		return x.PersonalityRef
	}
	return ""
}

func (x *SovereignContext) GetLedgerLink() string {
	if x != nil {
		return x.LedgerLink
	}
	return ""
}

func (x *SovereignContext) GetROIThreshold() float32 {
	if x != nil {
		return x.ROIThreshold
	}
	return 0
}

type ValidationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FilePath         string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	CodeContent      string                 `protobuf:"bytes,2,opt,name=code_content,json=codeContent,proto3" json:"code_content,omitempty"`
	TargetLayer      string                 `protobuf:"bytes,3,opt,name=target_layer,json=targetLayer,proto3" json:"target_layer,omitempty"` // "domain", "application", "infrastructure"
	ForbiddenImports []string               `protobuf:"bytes,4,rep,name=forbidden_imports,json=forbiddenImports,proto3" json:"forbidden_imports,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidationRequest) Reset() {
	*x = ValidationRequest{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRequest) ProtoMessage() {}

func (x *ValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRequest.ProtoReflect.Descriptor instead.
func (*ValidationRequest) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ValidationRequest) GetCodeContent() string {
	if x != nil {
		return x.CodeContent
	}
	return ""
}

func (x *ValidationRequest) GetTargetLayer() string {
	if x != nil {
		return x.TargetLayer
	}
	return ""
}

func (x *ValidationRequest) GetForbiddenImports() []string {
	if x != nil {
		return x.ForbiddenImports
	}
	return nil
}

type ValidationResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	IsConformant  bool                      `protobuf:"varint,1,opt,name=is_conformant,json=isConformant,proto3" json:"is_conformant,omitempty"`
	Violations    []*ArchitecturalViolation `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	HealthScore   string                    `protobuf:"bytes,3,opt,name=health_score,json=healthScore,proto3" json:"health_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResponse) Reset() {
	*x = ValidationResponse{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResponse) ProtoMessage() {}

func (x *ValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResponse.ProtoReflect.Descriptor instead.
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationResponse) GetIsConformant() bool {
	if x != nil {
		return x.IsConformant
	}
	return false
}

func (x *ValidationResponse) GetViolations() []*ArchitecturalViolation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *ValidationResponse) GetHealthScore() string {
	if x != nil {
		return x.HealthScore
	}
	return ""
}

type ArchitecturalViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ViolationType string                 `protobuf:"bytes,2,opt,name=violation_type,json=violationType,proto3" json:"violation_type,omitempty"` // "LAYER_INFECTION", "MISSING_INTERFACE", "ILLEGAL_IMPORT"
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Suggestion    string                 `protobuf:"bytes,4,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchitecturalViolation) Reset() {
	*x = ArchitecturalViolation{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchitecturalViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchitecturalViolation) ProtoMessage() {}

func (x *ArchitecturalViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchitecturalViolation.ProtoReflect.Descriptor instead.
func (*ArchitecturalViolation) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{3}
}

func (x *ArchitecturalViolation) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ArchitecturalViolation) GetViolationType() string {
	if x != nil {
		return x.ViolationType
	}
	return ""
}

func (x *ArchitecturalViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArchitecturalViolation) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

type NodeIdentity struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NodeId                string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PortType              string                 `protobuf:"bytes,2,opt,name=port_type,json=portType,proto3" json:"port_type,omitempty"`
	ImplementationVersion string                 `protobuf:"bytes,3,opt,name=implementation_version,json=implementationVersion,proto3" json:"implementation_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{4}
}

func (x *NodeIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeIdentity) GetPortType() string {
	if x != nil {
		return x.PortType
	}
	return ""
}

func (x *NodeIdentity) GetImplementationVersion() string {
	if x != nil {
		return x.ImplementationVersion
	}
	return ""
}

type AgentTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // "writer", "tester", "architect"
	ContextAnchor *EventId               `protobuf:"bytes,3,opt,name=context_anchor,json=contextAnchor,proto3" json:"context_anchor,omitempty"`
	PayloadTicket *MemoryTicket          `protobuf:"bytes,4,opt,name=payload_ticket,json=payloadTicket,proto3" json:"payload_ticket,omitempty"` // Datos vía MemoryTicket (Spec 10)
	SovereignCtx  *SovereignContext      `protobuf:"bytes,5,opt,name=sovereign_ctx,json=sovereignCtx,proto3" json:"sovereign_ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTask) Reset() {
	*x = AgentTask{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTask) ProtoMessage() {}

func (x *AgentTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTask.ProtoReflect.Descriptor instead.
func (*AgentTask) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{5}
}

func (x *AgentTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentTask) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentTask) GetContextAnchor() *EventId {
	if x != nil {
		return x.ContextAnchor
	}
	return nil
}

func (x *AgentTask) GetPayloadTicket() *MemoryTicket {
	if x != nil {
		return x.PayloadTicket
	}
	return nil
}

func (x *AgentTask) GetSovereignCtx() *SovereignContext {
	if x != nil {
		return x.SovereignCtx
	}
	return nil
}

type AgentIntent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SagaId         string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	IntentType     string                 `protobuf:"bytes,3,opt,name=intent_type,json=intentType,proto3" json:"intent_type,omitempty"` // "write_file", "execute_code", "query_graph"
	TargetResource string                 `protobuf:"bytes,4,opt,name=target_resource,json=targetResource,proto3" json:"target_resource,omitempty"`
	Payload        []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ParentEvent    *EventId               `protobuf:"bytes,6,opt,name=parent_event,json=parentEvent,proto3" json:"parent_event,omitempty"`
	IsShadow       bool                   `protobuf:"varint,7,opt,name=is_shadow,json=isShadow,proto3" json:"is_shadow,omitempty"` // No persistir en Git hasta consenso
	SovereignCtx   *SovereignContext      `protobuf:"bytes,8,opt,name=sovereign_ctx,json=sovereignCtx,proto3" json:"sovereign_ctx,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentIntent) Reset() {
	*x = AgentIntent{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIntent) ProtoMessage() {}

func (x *AgentIntent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIntent.ProtoReflect.Descriptor instead.
func (*AgentIntent) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{6}
}

func (x *AgentIntent) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *AgentIntent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentIntent) GetIntentType() string {
	if x != nil {
		return x.IntentType
	}
	return ""
}

func (x *AgentIntent) GetTargetResource() string {
	if x != nil {
		return x.TargetResource
	}
	return ""
}

func (x *AgentIntent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentIntent) GetParentEvent() *EventId {
	if x != nil {
		return x.ParentEvent
	}
	return nil
}

func (x *AgentIntent) GetIsShadow() bool {
	if x != nil {
		return x.IsShadow
	}
	return false
}

func (x *AgentIntent) GetSovereignCtx() *SovereignContext {
	if x != nil {
		return x.SovereignCtx
	}
	return nil
}

type TaskResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status         TaskResult_Status      `protobuf:"varint,2,opt,name=status,proto3,enum=dummie.v2.TaskResult_Status" json:"status,omitempty"`
	OutputTicket   *MemoryTicket          `protobuf:"bytes,3,opt,name=output_ticket,json=outputTicket,proto3" json:"output_ticket,omitempty"` // Resultado vía MemoryTicket
	ErrorSummary   string                 `protobuf:"bytes,4,opt,name=error_summary,json=errorSummary,proto3" json:"error_summary,omitempty"`
	TokensConsumed uint32                 `protobuf:"varint,5,opt,name=tokens_consumed,json=tokensConsumed,proto3" json:"tokens_consumed,omitempty"`
	EventId        *EventId               `protobuf:"bytes,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{7}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskResult_Status {
	if x != nil {
		return x.Status
	}
	return TaskResult_SUCCESS
}

func (x *TaskResult) GetOutputTicket() *MemoryTicket {
	if x != nil {
		return x.OutputTicket
	}
	return nil
}

func (x *TaskResult) GetErrorSummary() string {
	if x != nil {
		return x.ErrorSummary
	}
	return ""
}

func (x *TaskResult) GetTokensConsumed() uint32 {
	if x != nil {
		return x.TokensConsumed
	}
	return 0
}

func (x *TaskResult) GetEventId() *EventId {
	if x != nil {
		return x.EventId
	}
	return nil
}

type ThoughtTrace struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ThoughtFragment string                 `protobuf:"bytes,2,opt,name=thought_fragment,json=thoughtFragment,proto3" json:"thought_fragment,omitempty"`
	Confidence      float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CurrentPosition *EventId               `protobuf:"bytes,4,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThoughtTrace) Reset() {
	*x = ThoughtTrace{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThoughtTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThoughtTrace) ProtoMessage() {}

func (x *ThoughtTrace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThoughtTrace.ProtoReflect.Descriptor instead.
func (*ThoughtTrace) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{8}
}

func (x *ThoughtTrace) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ThoughtTrace) GetThoughtFragment() string {
	if x != nil {
		return x.ThoughtFragment
	}
	return ""
}

func (x *ThoughtTrace) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ThoughtTrace) GetCurrentPosition() *EventId {
	if x != nil {
		return x.CurrentPosition
	}
	return nil
}

type ExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"` // "python", "javascript", "bash"
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs     uint32                 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{9}
}

func (x *ExecutionRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecutionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecutionRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *ExecutionRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	TimedOut      bool                   `protobuf:"varint,4,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{10}
}

func (x *ExecutionResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecutionResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecutionResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecutionResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

type SkillData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillName     string                 `protobuf:"bytes,1,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	WasmBinary    []byte                 `protobuf:"bytes,2,opt,name=wasm_binary,json=wasmBinary,proto3" json:"wasm_binary,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillData) Reset() {
	*x = SkillData{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillData) ProtoMessage() {}

func (x *SkillData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillData.ProtoReflect.Descriptor instead.
func (*SkillData) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{11}
}

func (x *SkillData) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *SkillData) GetWasmBinary() []byte {
	if x != nil {
		return x.WasmBinary
	}
	return nil
}

func (x *SkillData) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type VectorClockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchIds     []string               `protobuf:"bytes,1,rep,name=branch_ids,json=branchIds,proto3" json:"branch_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClockRequest) Reset() {
	*x = VectorClockRequest{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClockRequest) ProtoMessage() {}

func (x *VectorClockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClockRequest.ProtoReflect.Descriptor instead.
func (*VectorClockRequest) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{12}
}

func (x *VectorClockRequest) GetBranchIds() []string {
	if x != nil {
		return x.BranchIds
	}
	return nil
}

type VectorClockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClockMap      map[string]uint64      `protobuf:"bytes,1,rep,name=clock_map,json=clockMap,proto3" json:"clock_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClockResponse) Reset() {
	*x = VectorClockResponse{}
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClockResponse) ProtoMessage() {}

func (x *VectorClockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_orchestration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClockResponse.ProtoReflect.Descriptor instead.
func (*VectorClockResponse) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_orchestration_proto_rawDescGZIP(), []int{13}
}

func (x *VectorClockResponse) GetClockMap() map[string]uint64 {
	if x != nil {
		return x.ClockMap
	}
	return nil
}

var File_proto_dummie_v2_orchestration_proto protoreflect.FileDescriptor

const file_proto_dummie_v2_orchestration_proto_rawDesc = "" +
	"\n" +
	"#proto/dummie/v2/orchestration.proto\x12\tdummie.v2\x1a\x1aproto/dummie/v2/core.proto\"\x81\x01\n" +
	"\x10SovereignContext\x12'\n" +
	"\x0fpersonality_ref\x18\x01 \x01(\tR\x0epersonalityRef\x12\x1f\n" +
	"\vledger_link\x18\x02 \x01(\tR\n" +
	"ledgerLink\x12#\n" +
	"\rROI_threshold\x18\x03 \x01(\x02R\fROIThreshold\"\xa3\x01\n" +
	"\x11ValidationRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12!\n" +
	"\fcode_content\x18\x02 \x01(\tR\vcodeContent\x12!\n" +
	"\ftarget_layer\x18\x03 \x01(\tR\vtargetLayer\x12+\n" +
	"\x11forbidden_imports\x18\x04 \x03(\tR\x10forbiddenImports\"\x9f\x01\n" +
	"\x12ValidationResponse\x12#\n" +
	"\ris_conformant\x18\x01 \x01(\bR\fisConformant\x12A\n" +
	"\n" +
	"violations\x18\x02 \x03(\v2!.dummie.v2.ArchitecturalViolationR\n" +
	"violations\x12!\n" +
	"\fhealth_score\x18\x03 \x01(\tR\vhealthScore\"\x9e\x01\n" +
	"\x16ArchitecturalViolation\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12%\n" +
	"\x0eviolation_type\x18\x02 \x01(\tR\rviolationType\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x04 \x01(\tR\n" +
	"suggestion\"{\n" +
	"\fNodeIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tport_type\x18\x02 \x01(\tR\bportType\x125\n" +
	"\x16implementation_version\x18\x03 \x01(\tR\x15implementationVersion\"\x80\x02\n" +
	"\tAgentTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x129\n" +
	"\x0econtext_anchor\x18\x03 \x01(\v2\x12.dummie.v2.EventIdR\rcontextAnchor\x12>\n" +
	"\x0epayload_ticket\x18\x04 \x01(\v2\x17.dummie.v2.MemoryTicketR\rpayloadTicket\x12@\n" +
	"\rsovereign_ctx\x18\x05 \x01(\v2\x1b.dummie.v2.SovereignContextR\fsovereignCtx\"\xbb\x02\n" +
	"\vAgentIntent\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1f\n" +
	"\vintent_type\x18\x03 \x01(\tR\n" +
	"intentType\x12'\n" +
	"\x0ftarget_resource\x18\x04 \x01(\tR\x0etargetResource\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x125\n" +
	"\fparent_event\x18\x06 \x01(\v2\x12.dummie.v2.EventIdR\vparentEvent\x12\x1b\n" +
	"\tis_shadow\x18\a \x01(\bR\bisShadow\x12@\n" +
	"\rsovereign_ctx\x18\b \x01(\v2\x1b.dummie.v2.SovereignContextR\fsovereignCtx\"\xca\x02\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.dummie.v2.TaskResult.StatusR\x06status\x12<\n" +
	"\routput_ticket\x18\x03 \x01(\v2\x17.dummie.v2.MemoryTicketR\foutputTicket\x12#\n" +
	"\rerror_summary\x18\x04 \x01(\tR\ferrorSummary\x12'\n" +
	"\x0ftokens_consumed\x18\x05 \x01(\rR\x0etokensConsumed\x12-\n" +
	"\bevent_id\x18\x06 \x01(\v2\x12.dummie.v2.EventIdR\aeventId\"2\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\x12\x0e\n" +
	"\n" +
	"QUARANTINE\x10\x02\"\xb3\x01\n" +
	"\fThoughtTrace\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x10thought_fragment\x18\x02 \x01(\tR\x0fthoughtFragment\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12=\n" +
	"\x10current_position\x18\x04 \x01(\v2\x12.dummie.v2.EventIdR\x0fcurrentPosition\"\xe2\x01\n" +
	"\x10ExecutionRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12C\n" +
	"\benv_vars\x18\x03 \x03(\v2(.dummie.v2.ExecutionRequest.EnvVarsEntryR\aenvVars\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x11ExecutionResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1b\n" +
	"\ttimed_out\x18\x04 \x01(\bR\btimedOut\"p\n" +
	"\tSkillData\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x01 \x01(\tR\tskillName\x12\x1f\n" +
	"\vwasm_binary\x18\x02 \x01(\fR\n" +
	"wasmBinary\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\"3\n" +
	"\x12VectorClockRequest\x12\x1d\n" +
	"\n" +
	"branch_ids\x18\x01 \x03(\tR\tbranchIds\"\x9d\x01\n" +
	"\x13VectorClockResponse\x12I\n" +
	"\tclock_map\x18\x01 \x03(\v2,.dummie.v2.VectorClockResponse.ClockMapEntryR\bclockMap\x1a;\n" +
	"\rClockMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x012\xd5\x01\n" +
	"\x14OrchestrationService\x12:\n" +
	"\vExecuteTask\x12\x14.dummie.v2.AgentTask\x1a\x15.dummie.v2.TaskResult\x12B\n" +
	"\rStreamThought\x12\x16.dummie.v2.AgentIntent\x1a\x17.dummie.v2.ThoughtTrace0\x01\x12=\n" +
	"\fSubmitIntent\x12\x16.dummie.v2.AgentIntent\x1a\x15.dummie.v2.TaskResult2\x9c\x01\n" +
	"\x17SandboxExecutionService\x12D\n" +
	"\aRunCode\x12\x1b.dummie.v2.ExecutionRequest\x1a\x1c.dummie.v2.ExecutionResponse\x12;\n" +
	"\fInstallSkill\x12\x14.dummie.v2.SkillData\x1a\x15.dummie.v2.TaskResult2\xd9\x01\n" +
	"\x11TimeKeeperService\x12O\n" +
	"\x0eGetVectorClock\x12\x1d.dummie.v2.VectorClockRequest\x1a\x1e.dummie.v2.VectorClockResponse\x12:\n" +
	"\rRegisterEvent\x12\x12.dummie.v2.EventId\x1a\x15.dummie.v2.TaskResult\x127\n" +
	"\n" +
	"TruncateKV\x12\x12.dummie.v2.EventId\x1a\x15.dummie.v2.TaskResult2\xbb\x01\n" +
	"\x1eArchitecturalValidationService\x12Q\n" +
	"\x12ValidateConformity\x12\x1c.dummie.v2.ValidationRequest\x1a\x1d.dummie.v2.ValidationResponse\x12F\n" +
	"\x14CheckAtomicIsolation\x12\x17.dummie.v2.NodeIdentity\x1a\x15.dummie.v2.TaskResultB&Z$io.dummie.v2/nervous/proto;dummie_v2b\x06proto3"

var (
	file_proto_dummie_v2_orchestration_proto_rawDescOnce sync.Once
	file_proto_dummie_v2_orchestration_proto_rawDescData []byte
)

func file_proto_dummie_v2_orchestration_proto_rawDescGZIP() []byte {
	file_proto_dummie_v2_orchestration_proto_rawDescOnce.Do(func() {
		file_proto_dummie_v2_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dummie_v2_orchestration_proto_rawDesc), len(file_proto_dummie_v2_orchestration_proto_rawDesc)))
	})
	return file_proto_dummie_v2_orchestration_proto_rawDescData
}

var file_proto_dummie_v2_orchestration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dummie_v2_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_dummie_v2_orchestration_proto_goTypes = []any{
	(TaskResult_Status)(0),         // 0: dummie.v2.TaskResult.Status
	(*SovereignContext)(nil),       // 1: dummie.v2.SovereignContext
	(*ValidationRequest)(nil),      // 2: dummie.v2.ValidationRequest
	(*ValidationResponse)(nil),     // 3: dummie.v2.ValidationResponse
	(*ArchitecturalViolation)(nil), // 4: dummie.v2.ArchitecturalViolation
	(*NodeIdentity)(nil),           // 5: dummie.v2.NodeIdentity
	(*AgentTask)(nil),              // 6: dummie.v2.AgentTask
	(*AgentIntent)(nil),            // 7: dummie.v2.AgentIntent
	(*TaskResult)(nil),             // 8: dummie.v2.TaskResult
	(*ThoughtTrace)(nil),           // 9: dummie.v2.ThoughtTrace
	(*ExecutionRequest)(nil),       // 10: dummie.v2.ExecutionRequest
	(*ExecutionResponse)(nil),      // 11: dummie.v2.ExecutionResponse
	(*SkillData)(nil),              // 12: dummie.v2.SkillData
	(*VectorClockRequest)(nil),     // 13: dummie.v2.VectorClockRequest
	(*VectorClockResponse)(nil),    // 14: dummie.v2.VectorClockResponse
	nil,                            // 15: dummie.v2.ExecutionRequest.EnvVarsEntry
	nil,                            // 16: dummie.v2.VectorClockResponse.ClockMapEntry
	(*EventId)(nil),                // 17: dummie.v2.EventId
	(*MemoryTicket)(nil),           // 18: dummie.v2.MemoryTicket
}
var file_proto_dummie_v2_orchestration_proto_depIdxs = []int32{
	4,  // 0: dummie.v2.ValidationResponse.violations:type_name -> dummie.v2.ArchitecturalViolation
	17, // 1: dummie.v2.AgentTask.context_anchor:type_name -> dummie.v2.EventId
	18, // 2: dummie.v2.AgentTask.payload_ticket:type_name -> dummie.v2.MemoryTicket
	1,  // 3: dummie.v2.AgentTask.sovereign_ctx:type_name -> dummie.v2.SovereignContext
	17, // 4: dummie.v2.AgentIntent.parent_event:type_name -> dummie.v2.EventId
	1,  // 5: dummie.v2.AgentIntent.sovereign_ctx:type_name -> dummie.v2.SovereignContext
	0,  // 6: dummie.v2.TaskResult.status:type_name -> dummie.v2.TaskResult.Status
	18, // 7: dummie.v2.TaskResult.output_ticket:type_name -> dummie.v2.MemoryTicket
	17, // 8: dummie.v2.TaskResult.event_id:type_name -> dummie.v2.EventId
	17, // 9: dummie.v2.ThoughtTrace.current_position:type_name -> dummie.v2.EventId
	15, // 10: dummie.v2.ExecutionRequest.env_vars:type_name -> dummie.v2.ExecutionRequest.EnvVarsEntry
	16, // 11: dummie.v2.VectorClockResponse.clock_map:type_name -> dummie.v2.VectorClockResponse.ClockMapEntry
	6,  // 12: dummie.v2.OrchestrationService.ExecuteTask:input_type -> dummie.v2.AgentTask
	7,  // 13: dummie.v2.OrchestrationService.StreamThought:input_type -> dummie.v2.AgentIntent
	7,  // 14: dummie.v2.OrchestrationService.SubmitIntent:input_type -> dummie.v2.AgentIntent
	10, // 15: dummie.v2.SandboxExecutionService.RunCode:input_type -> dummie.v2.ExecutionRequest
	12, // 16: dummie.v2.SandboxExecutionService.InstallSkill:input_type -> dummie.v2.SkillData
	13, // 17: dummie.v2.TimeKeeperService.GetVectorClock:input_type -> dummie.v2.VectorClockRequest
	17, // 18: dummie.v2.TimeKeeperService.RegisterEvent:input_type -> dummie.v2.EventId
	17, // 19: dummie.v2.TimeKeeperService.TruncateKV:input_type -> dummie.v2.EventId
	2,  // 20: dummie.v2.ArchitecturalValidationService.ValidateConformity:input_type -> dummie.v2.ValidationRequest
	5,  // 21: dummie.v2.ArchitecturalValidationService.CheckAtomicIsolation:input_type -> dummie.v2.NodeIdentity
	8,  // 22: dummie.v2.OrchestrationService.ExecuteTask:output_type -> dummie.v2.TaskResult
	9,  // 23: dummie.v2.OrchestrationService.StreamThought:output_type -> dummie.v2.ThoughtTrace
	8,  // 24: dummie.v2.OrchestrationService.SubmitIntent:output_type -> dummie.v2.TaskResult
	11, // 25: dummie.v2.SandboxExecutionService.RunCode:output_type -> dummie.v2.ExecutionResponse
	8,  // 26: dummie.v2.SandboxExecutionService.InstallSkill:output_type -> dummie.v2.TaskResult
	14, // 27: dummie.v2.TimeKeeperService.GetVectorClock:output_type -> dummie.v2.VectorClockResponse
	8,  // 28: dummie.v2.TimeKeeperService.RegisterEvent:output_type -> dummie.v2.TaskResult
	8,  // 29: dummie.v2.TimeKeeperService.TruncateKV:output_type -> dummie.v2.TaskResult
	3,  // 30: dummie.v2.ArchitecturalValidationService.ValidateConformity:output_type -> dummie.v2.ValidationResponse
	8,  // 31: dummie.v2.ArchitecturalValidationService.CheckAtomicIsolation:output_type -> dummie.v2.TaskResult
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_dummie_v2_orchestration_proto_init() }
func file_proto_dummie_v2_orchestration_proto_init() {
	if File_proto_dummie_v2_orchestration_proto != nil {
		return
	}
	file_proto_dummie_v2_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dummie_v2_orchestration_proto_rawDesc), len(file_proto_dummie_v2_orchestration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_dummie_v2_orchestration_proto_goTypes,
		DependencyIndexes: file_proto_dummie_v2_orchestration_proto_depIdxs,
		EnumInfos:         file_proto_dummie_v2_orchestration_proto_enumTypes,
		MessageInfos:      file_proto_dummie_v2_orchestration_proto_msgTypes,
	}.Build()
	File_proto_dummie_v2_orchestration_proto = out.File
	file_proto_dummie_v2_orchestration_proto_goTypes = nil
	file_proto_dummie_v2_orchestration_proto_depIdxs = nil
}
