// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/dummie/v2/memory.proto

package dummie_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntentType int32

const (
	IntentType_INTENT_UNSPECIFIED IntentType = 0
	IntentType_OBSERVATION        IntentType = 1 // Lectura de estado
	IntentType_FABRICATION        IntentType = 2 // Creación/Escritura de nuevo conocimiento
	IntentType_MUTATION           IntentType = 3 // Refactor/Cambio de conocimiento existente
	IntentType_RESOLUTION         IntentType = 4 // Cierre de ambigüedad (Jidoka)
	IntentType_AUDIT              IntentType = 5 // Verificación/Validación (Sentinel)
	IntentType_CRYSTALLIZATION    IntentType = 6 // Destilación de Skill/Regla
)

// Enum value maps for IntentType.
var (
	IntentType_name = map[int32]string{
		0: "INTENT_UNSPECIFIED",
		1: "OBSERVATION",
		2: "FABRICATION",
		3: "MUTATION",
		4: "RESOLUTION",
		5: "AUDIT",
		6: "CRYSTALLIZATION",
	}
	IntentType_value = map[string]int32{
		"INTENT_UNSPECIFIED": 0,
		"OBSERVATION":        1,
		"FABRICATION":        2,
		"MUTATION":           3,
		"RESOLUTION":         4,
		"AUDIT":              5,
		"CRYSTALLIZATION":    6,
	}
)

func (x IntentType) Enum() *IntentType {
	p := new(IntentType)
	*p = x
	return p
}

func (x IntentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dummie_v2_memory_proto_enumTypes[0].Descriptor()
}

func (IntentType) Type() protoreflect.EnumType {
	return &file_proto_dummie_v2_memory_proto_enumTypes[0]
}

func (x IntentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntentType.Descriptor instead.
func (IntentType) EnumDescriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{0}
}

// ==========================================
// DECISION LEDGER RECORD
// ==========================================
// Prueba criptográfica inmutable de resoluciones de diseño.
type DecisionRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DecisionId        string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Rationale         string                 `protobuf:"bytes,2,opt,name=rationale,proto3" json:"rationale,omitempty"`
	ImpactBlastRadius string                 `protobuf:"bytes,3,opt,name=impact_blast_radius,json=impactBlastRadius,proto3" json:"impact_blast_radius,omitempty"`
	Context           *SixDimensionalContext `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`                                             // Origen de la decisión
	TargetCausalHash  string                 `protobuf:"bytes,5,opt,name=target_causal_hash,json=targetCausalHash,proto3" json:"target_causal_hash,omitempty"` // El nodo 4D-TES sobre el que recae el fallo
	WitnessHash       string                 `protobuf:"bytes,6,opt,name=witness_hash,json=witnessHash,proto3" json:"witness_hash,omitempty"`                  // Firma criptográfica del auditor (Sentinel/PAH)
	Tick              uint64                 `protobuf:"varint,7,opt,name=tick,proto3" json:"tick,omitempty"`                                                  // Reloj de Lamport de la resolución
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DecisionRecord) Reset() {
	*x = DecisionRecord{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRecord) ProtoMessage() {}

func (x *DecisionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRecord.ProtoReflect.Descriptor instead.
func (*DecisionRecord) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionRecord) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *DecisionRecord) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *DecisionRecord) GetImpactBlastRadius() string {
	if x != nil {
		return x.ImpactBlastRadius
	}
	return ""
}

func (x *DecisionRecord) GetContext() *SixDimensionalContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DecisionRecord) GetTargetCausalHash() string {
	if x != nil {
		return x.TargetCausalHash
	}
	return ""
}

func (x *DecisionRecord) GetWitnessHash() string {
	if x != nil {
		return x.WitnessHash
	}
	return ""
}

func (x *DecisionRecord) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

// Representa una lección aprendida tras un fallo o refactorización.
type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	LessonId      string                 `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"` // Identificador único (LES-XXX)
	Issue         string                 `protobuf:"bytes,3,opt,name=issue,proto3" json:"issue,omitempty"`                       // El problema detectado
	Correction    string                 `protobuf:"bytes,4,opt,name=correction,proto3" json:"correction,omitempty"`             // Cómo se solucionó
	Prevention    string                 `protobuf:"bytes,5,opt,name=prevention,proto3" json:"prevention,omitempty"`             // Cómo evitarlo en el futuro
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{1}
}

func (x *Lesson) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Lesson) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *Lesson) GetIssue() string {
	if x != nil {
		return x.Issue
	}
	return ""
}

func (x *Lesson) GetCorrection() string {
	if x != nil {
		return x.Correction
	}
	return ""
}

func (x *Lesson) GetPrevention() string {
	if x != nil {
		return x.Prevention
	}
	return ""
}

// Representa la resolución de una indeterminación lógica.
type Ambiguity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	AmbiguityId   string                 `protobuf:"bytes,2,opt,name=ambiguity_id,json=ambiguityId,proto3" json:"ambiguity_id,omitempty"` // Identificador único (AMB-XXX)
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                            // El escenario ambiguo
	Resolution    string                 `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`                      // La aclaración final
	Impact        string                 `protobuf:"bytes,5,opt,name=impact,proto3" json:"impact,omitempty"`                              // Qué partes del sistema se ven afectadas
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ambiguity) Reset() {
	*x = Ambiguity{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ambiguity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ambiguity) ProtoMessage() {}

func (x *Ambiguity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ambiguity.ProtoReflect.Descriptor instead.
func (*Ambiguity) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{2}
}

func (x *Ambiguity) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Ambiguity) GetAmbiguityId() string {
	if x != nil {
		return x.AmbiguityId
	}
	return ""
}

func (x *Ambiguity) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Ambiguity) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *Ambiguity) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

// Contenedor para exportación masiva o persistencia en frío.
type SessionCrystallization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decisions     []*DecisionRecord      `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	Lessons       []*Lesson              `protobuf:"bytes,2,rep,name=lessons,proto3" json:"lessons,omitempty"`
	Ambiguities   []*Ambiguity           `protobuf:"bytes,3,rep,name=ambiguities,proto3" json:"ambiguities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCrystallization) Reset() {
	*x = SessionCrystallization{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCrystallization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCrystallization) ProtoMessage() {}

func (x *SessionCrystallization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCrystallization.ProtoReflect.Descriptor instead.
func (*SessionCrystallization) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{3}
}

func (x *SessionCrystallization) GetDecisions() []*DecisionRecord {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *SessionCrystallization) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

func (x *SessionCrystallization) GetAmbiguities() []*Ambiguity {
	if x != nil {
		return x.Ambiguities
	}
	return nil
}

// ==========================================
// 6D-CONTEXT: THE DETERMINISTIC VECTOR
// ==========================================
// Un vector de coordenadas absolutas que no admite ambigüedad.
// Si falta una coordenada, el validador emite un SegFault Lógico.
type SixDimensionalContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [3D Espacial] Coordenadas en el Grafo Ontológico
	LocusX string `protobuf:"bytes,1,opt,name=locus_x,json=locusX,proto3" json:"locus_x,omitempty"` // ID del Bounded Context (ej. "domain.fabrication")
	LocusY string `protobuf:"bytes,2,opt,name=locus_y,json=locusY,proto3" json:"locus_y,omitempty"` // ID del Aggregate Root (ej. "MemoryNode")
	LocusZ string `protobuf:"bytes,3,opt,name=locus_z,json=locusZ,proto3" json:"locus_z,omitempty"` // ID de la Entidad Atómica (ej. "models.py")
	// [1D Temporal] La Flecha del Tiempo
	LamportT uint64 `protobuf:"varint,4,opt,name=lamport_t,json=lamportT,proto3" json:"lamport_t,omitempty"` // Contador monotónico local de causalidad
	// [1D Soberanía]
	AuthorityA AuthorityLevel `protobuf:"varint,5,opt,name=authority_a,json=authorityA,proto3,enum=dummie.v2.AuthorityLevel" json:"authority_a,omitempty"` // Peso determinista en la resolución de conflictos
	// [1D Causalidad Intencional]
	IntentI       IntentType `protobuf:"varint,6,opt,name=intent_i,json=intentI,proto3,enum=io.dummie.v2.memory.IntentType" json:"intent_i,omitempty"` // Razón inmutable de la existencia del nodo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SixDimensionalContext) Reset() {
	*x = SixDimensionalContext{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SixDimensionalContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SixDimensionalContext) ProtoMessage() {}

func (x *SixDimensionalContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SixDimensionalContext.ProtoReflect.Descriptor instead.
func (*SixDimensionalContext) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{4}
}

func (x *SixDimensionalContext) GetLocusX() string {
	if x != nil {
		return x.LocusX
	}
	return ""
}

func (x *SixDimensionalContext) GetLocusY() string {
	if x != nil {
		return x.LocusY
	}
	return ""
}

func (x *SixDimensionalContext) GetLocusZ() string {
	if x != nil {
		return x.LocusZ
	}
	return ""
}

func (x *SixDimensionalContext) GetLamportT() uint64 {
	if x != nil {
		return x.LamportT
	}
	return 0
}

func (x *SixDimensionalContext) GetAuthorityA() AuthorityLevel {
	if x != nil {
		return x.AuthorityA
	}
	return AuthorityLevel_AUTHORITY_UNSPECIFIED
}

func (x *SixDimensionalContext) GetIntentI() IntentType {
	if x != nil {
		return x.IntentI
	}
	return IntentType_INTENT_UNSPECIFIED
}

// ==========================================
// 4D-TES: IMMUTABLE MEMORY NODE
// ==========================================
// Entrada atómica en el Event Sourcing. Mutar implica derivar una nueva rama.
type MemoryNode4DTES struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CausalHash    string                 `protobuf:"bytes,1,opt,name=causal_hash,json=causalHash,proto3" json:"causal_hash,omitempty"`       // SHA-256(parent_hash + payload_hash + 6d_context)
	ParentHashes  []string               `protobuf:"bytes,2,rep,name=parent_hashes,json=parentHashes,proto3" json:"parent_hashes,omitempty"` // Puntero criptográfico al nodo anterior (Join-semilattice)
	Context       *SixDimensionalContext `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                               // Coordenadas absolutas de génesis
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                               // Excitación inmutable (Zstd compressed JSON o AST)
	PayloadHash   string                 `protobuf:"bytes,5,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`    // Verificación de integridad del payload aislado
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryNode4DTES) Reset() {
	*x = MemoryNode4DTES{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryNode4DTES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryNode4DTES) ProtoMessage() {}

func (x *MemoryNode4DTES) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryNode4DTES.ProtoReflect.Descriptor instead.
func (*MemoryNode4DTES) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryNode4DTES) GetCausalHash() string {
	if x != nil {
		return x.CausalHash
	}
	return ""
}

func (x *MemoryNode4DTES) GetParentHashes() []string {
	if x != nil {
		return x.ParentHashes
	}
	return nil
}

func (x *MemoryNode4DTES) GetContext() *SixDimensionalContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *MemoryNode4DTES) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MemoryNode4DTES) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

// === Ledger de Sesión (Spec 36) ===
// Captura el "Stream of Consciousness" efímero.
type EgoState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Tick          uint64                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	ThoughtVector string                 `protobuf:"bytes,3,opt,name=thought_vector,json=thoughtVector,proto3" json:"thought_vector,omitempty"` // Representación latente o descripción en texto
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                                    // Intención física o llamada a herramienta
	Context       *SixDimensionalContext `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`                                  // Contexto en el momento de la inferencia
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgoState) Reset() {
	*x = EgoState{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgoState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgoState) ProtoMessage() {}

func (x *EgoState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgoState.ProtoReflect.Descriptor instead.
func (*EgoState) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{6}
}

func (x *EgoState) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EgoState) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *EgoState) GetThoughtVector() string {
	if x != nil {
		return x.ThoughtVector
	}
	return ""
}

func (x *EgoState) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EgoState) GetContext() *SixDimensionalContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// === Ontological Certainty Map (Spec 42) ===
// Cuantifica el determinismo de una capa.
type LayerCertainty struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LayerName           string                 `protobuf:"bytes,1,opt,name=layer_name,json=layerName,proto3" json:"layer_name,omitempty"`                         // ej. "L2_Brain", "L4_Edge"
	CertaintyScore      float32                `protobuf:"fixed32,2,opt,name=certainty_score,json=certaintyScore,proto3" json:"certainty_score,omitempty"`        // [0.0 - 1.0]
	IsTerraIncognita    bool                   `protobuf:"varint,3,opt,name=is_terra_incognita,json=isTerraIncognita,proto3" json:"is_terra_incognita,omitempty"` // Código sin representation en doc
	TestsPassing        uint32                 `protobuf:"varint,4,opt,name=tests_passing,json=testsPassing,proto3" json:"tests_passing,omitempty"`
	UnverifiedMutations uint32                 `protobuf:"varint,5,opt,name=unverified_mutations,json=unverifiedMutations,proto3" json:"unverified_mutations,omitempty"` // Cambios sin test asociado
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LayerCertainty) Reset() {
	*x = LayerCertainty{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerCertainty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerCertainty) ProtoMessage() {}

func (x *LayerCertainty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerCertainty.ProtoReflect.Descriptor instead.
func (*LayerCertainty) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{7}
}

func (x *LayerCertainty) GetLayerName() string {
	if x != nil {
		return x.LayerName
	}
	return ""
}

func (x *LayerCertainty) GetCertaintyScore() float32 {
	if x != nil {
		return x.CertaintyScore
	}
	return 0
}

func (x *LayerCertainty) GetIsTerraIncognita() bool {
	if x != nil {
		return x.IsTerraIncognita
	}
	return false
}

func (x *LayerCertainty) GetTestsPassing() uint32 {
	if x != nil {
		return x.TestsPassing
	}
	return 0
}

func (x *LayerCertainty) GetUnverifiedMutations() uint32 {
	if x != nil {
		return x.UnverifiedMutations
	}
	return 0
}

type OntologicalMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layers        []*LayerCertainty      `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OntologicalMap) Reset() {
	*x = OntologicalMap{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OntologicalMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OntologicalMap) ProtoMessage() {}

func (x *OntologicalMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OntologicalMap.ProtoReflect.Descriptor instead.
func (*OntologicalMap) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{8}
}

func (x *OntologicalMap) GetLayers() []*LayerCertainty {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *OntologicalMap) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// === A2A Discovery Protocol (Spec 37) ===
// Latidos (Heartbeats) emitidos a NATS para presencia.
type AgentPresenceHeartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ExpertiseTags  []string               `protobuf:"bytes,2,rep,name=expertise_tags,json=expertiseTags,proto3" json:"expertise_tags,omitempty"`    // Skills registradas (Spec 28)
	CurrentLoad    float32                `protobuf:"fixed32,3,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`        // Saturación cognitiva [0.0 - 1.0]
	AuthorityLevel string                 `protobuf:"bytes,4,opt,name=authority_level,json=authorityLevel,proto3" json:"authority_level,omitempty"` // Delegación de capa base
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentPresenceHeartbeat) Reset() {
	*x = AgentPresenceHeartbeat{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPresenceHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPresenceHeartbeat) ProtoMessage() {}

func (x *AgentPresenceHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPresenceHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentPresenceHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{9}
}

func (x *AgentPresenceHeartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentPresenceHeartbeat) GetExpertiseTags() []string {
	if x != nil {
		return x.ExpertiseTags
	}
	return nil
}

func (x *AgentPresenceHeartbeat) GetCurrentLoad() float32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *AgentPresenceHeartbeat) GetAuthorityLevel() string {
	if x != nil {
		return x.AuthorityLevel
	}
	return ""
}

// ==========================================
// CRYSTALLIZED SKILL (PROCEDURAL MEMORY)
// ==========================================
// Habilidad destilada con proveniencia causal inquebrantable (Spec 38)
type CrystallizedSkill struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SkillId     string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	YamlPayload string                 `protobuf:"bytes,2,opt,name=yaml_payload,json=yamlPayload,proto3" json:"yaml_payload,omitempty"` // El contrato YAML ejecutable
	// Proveniencia: Lista de nodos 4D-TES que originaron este aprendizaje
	SourceCausalHashes []string `protobuf:"bytes,3,rep,name=source_causal_hashes,json=sourceCausalHashes,proto3" json:"source_causal_hashes,omitempty"`
	// Firma criptográfica que previene tampering de la habilidad
	SkillHash     string `protobuf:"bytes,4,opt,name=skill_hash,json=skillHash,proto3" json:"skill_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrystallizedSkill) Reset() {
	*x = CrystallizedSkill{}
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrystallizedSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrystallizedSkill) ProtoMessage() {}

func (x *CrystallizedSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummie_v2_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrystallizedSkill.ProtoReflect.Descriptor instead.
func (*CrystallizedSkill) Descriptor() ([]byte, []int) {
	return file_proto_dummie_v2_memory_proto_rawDescGZIP(), []int{10}
}

func (x *CrystallizedSkill) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *CrystallizedSkill) GetYamlPayload() string {
	if x != nil {
		return x.YamlPayload
	}
	return ""
}

func (x *CrystallizedSkill) GetSourceCausalHashes() []string {
	if x != nil {
		return x.SourceCausalHashes
	}
	return nil
}

func (x *CrystallizedSkill) GetSkillHash() string {
	if x != nil {
		return x.SkillHash
	}
	return ""
}

var File_proto_dummie_v2_memory_proto protoreflect.FileDescriptor

const file_proto_dummie_v2_memory_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/dummie/v2/memory.proto\x12\x13io.dummie.v2.memory\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aproto/dummie/v2/core.proto\"\xaa\x02\n" +
	"\x0eDecisionRecord\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x1c\n" +
	"\trationale\x18\x02 \x01(\tR\trationale\x12.\n" +
	"\x13impact_blast_radius\x18\x03 \x01(\tR\x11impactBlastRadius\x12D\n" +
	"\acontext\x18\x04 \x01(\v2*.io.dummie.v2.memory.SixDimensionalContextR\acontext\x12,\n" +
	"\x12target_causal_hash\x18\x05 \x01(\tR\x10targetCausalHash\x12!\n" +
	"\fwitness_hash\x18\x06 \x01(\tR\vwitnessHash\x12\x12\n" +
	"\x04tick\x18\a \x01(\x04R\x04tick\"\x8f\x01\n" +
	"\x06Lesson\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12\x1b\n" +
	"\tlesson_id\x18\x02 \x01(\tR\blessonId\x12\x14\n" +
	"\x05issue\x18\x03 \x01(\tR\x05issue\x12\x1e\n" +
	"\n" +
	"correction\x18\x04 \x01(\tR\n" +
	"correction\x12\x1e\n" +
	"\n" +
	"prevention\x18\x05 \x01(\tR\n" +
	"prevention\"\x94\x01\n" +
	"\tAmbiguity\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12!\n" +
	"\fambiguity_id\x18\x02 \x01(\tR\vambiguityId\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\tR\n" +
	"resolution\x12\x16\n" +
	"\x06impact\x18\x05 \x01(\tR\x06impact\"\xd4\x01\n" +
	"\x16SessionCrystallization\x12A\n" +
	"\tdecisions\x18\x01 \x03(\v2#.io.dummie.v2.memory.DecisionRecordR\tdecisions\x125\n" +
	"\alessons\x18\x02 \x03(\v2\x1b.io.dummie.v2.memory.LessonR\alessons\x12@\n" +
	"\vambiguities\x18\x03 \x03(\v2\x1e.io.dummie.v2.memory.AmbiguityR\vambiguities\"\xf7\x01\n" +
	"\x15SixDimensionalContext\x12\x17\n" +
	"\alocus_x\x18\x01 \x01(\tR\x06locusX\x12\x17\n" +
	"\alocus_y\x18\x02 \x01(\tR\x06locusY\x12\x17\n" +
	"\alocus_z\x18\x03 \x01(\tR\x06locusZ\x12\x1b\n" +
	"\tlamport_t\x18\x04 \x01(\x04R\blamportT\x12:\n" +
	"\vauthority_a\x18\x05 \x01(\x0e2\x19.dummie.v2.AuthorityLevelR\n" +
	"authorityA\x12:\n" +
	"\bintent_i\x18\x06 \x01(\x0e2\x1f.io.dummie.v2.memory.IntentTypeR\aintentI\"\xda\x01\n" +
	"\x0fMemoryNode4DTES\x12\x1f\n" +
	"\vcausal_hash\x18\x01 \x01(\tR\n" +
	"causalHash\x12#\n" +
	"\rparent_hashes\x18\x02 \x03(\tR\fparentHashes\x12D\n" +
	"\acontext\x18\x03 \x01(\v2*.io.dummie.v2.memory.SixDimensionalContextR\acontext\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12!\n" +
	"\fpayload_hash\x18\x05 \x01(\tR\vpayloadHash\"\xbe\x01\n" +
	"\bEgoState\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x04R\x04tick\x12%\n" +
	"\x0ethought_vector\x18\x03 \x01(\tR\rthoughtVector\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12D\n" +
	"\acontext\x18\x05 \x01(\v2*.io.dummie.v2.memory.SixDimensionalContextR\acontext\"\xde\x01\n" +
	"\x0eLayerCertainty\x12\x1d\n" +
	"\n" +
	"layer_name\x18\x01 \x01(\tR\tlayerName\x12'\n" +
	"\x0fcertainty_score\x18\x02 \x01(\x02R\x0ecertaintyScore\x12,\n" +
	"\x12is_terra_incognita\x18\x03 \x01(\bR\x10isTerraIncognita\x12#\n" +
	"\rtests_passing\x18\x04 \x01(\rR\ftestsPassing\x121\n" +
	"\x14unverified_mutations\x18\x05 \x01(\rR\x13unverifiedMutations\"\x88\x01\n" +
	"\x0eOntologicalMap\x12;\n" +
	"\x06layers\x18\x01 \x03(\v2#.io.dummie.v2.memory.LayerCertaintyR\x06layers\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa6\x01\n" +
	"\x16AgentPresenceHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12%\n" +
	"\x0eexpertise_tags\x18\x02 \x03(\tR\rexpertiseTags\x12!\n" +
	"\fcurrent_load\x18\x03 \x01(\x02R\vcurrentLoad\x12'\n" +
	"\x0fauthority_level\x18\x04 \x01(\tR\x0eauthorityLevel\"\xa2\x01\n" +
	"\x11CrystallizedSkill\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12!\n" +
	"\fyaml_payload\x18\x02 \x01(\tR\vyamlPayload\x120\n" +
	"\x14source_causal_hashes\x18\x03 \x03(\tR\x12sourceCausalHashes\x12\x1d\n" +
	"\n" +
	"skill_hash\x18\x04 \x01(\tR\tskillHash*\x84\x01\n" +
	"\n" +
	"IntentType\x12\x16\n" +
	"\x12INTENT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOBSERVATION\x10\x01\x12\x0f\n" +
	"\vFABRICATION\x10\x02\x12\f\n" +
	"\bMUTATION\x10\x03\x12\x0e\n" +
	"\n" +
	"RESOLUTION\x10\x04\x12\t\n" +
	"\x05AUDIT\x10\x05\x12\x13\n" +
	"\x0fCRYSTALLIZATION\x10\x06B&Z$io.dummie.v2/nervous/proto;dummie_v2b\x06proto3"

var (
	file_proto_dummie_v2_memory_proto_rawDescOnce sync.Once
	file_proto_dummie_v2_memory_proto_rawDescData []byte
)

func file_proto_dummie_v2_memory_proto_rawDescGZIP() []byte {
	file_proto_dummie_v2_memory_proto_rawDescOnce.Do(func() {
		file_proto_dummie_v2_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dummie_v2_memory_proto_rawDesc), len(file_proto_dummie_v2_memory_proto_rawDesc)))
	})
	return file_proto_dummie_v2_memory_proto_rawDescData
}

var file_proto_dummie_v2_memory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dummie_v2_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_dummie_v2_memory_proto_goTypes = []any{
	(IntentType)(0),                // 0: io.dummie.v2.memory.IntentType
	(*DecisionRecord)(nil),         // 1: io.dummie.v2.memory.DecisionRecord
	(*Lesson)(nil),                 // 2: io.dummie.v2.memory.Lesson
	(*Ambiguity)(nil),              // 3: io.dummie.v2.memory.Ambiguity
	(*SessionCrystallization)(nil), // 4: io.dummie.v2.memory.SessionCrystallization
	(*SixDimensionalContext)(nil),  // 5: io.dummie.v2.memory.SixDimensionalContext
	(*MemoryNode4DTES)(nil),        // 6: io.dummie.v2.memory.MemoryNode4DTES
	(*EgoState)(nil),               // 7: io.dummie.v2.memory.EgoState
	(*LayerCertainty)(nil),         // 8: io.dummie.v2.memory.LayerCertainty
	(*OntologicalMap)(nil),         // 9: io.dummie.v2.memory.OntologicalMap
	(*AgentPresenceHeartbeat)(nil), // 10: io.dummie.v2.memory.AgentPresenceHeartbeat
	(*CrystallizedSkill)(nil),      // 11: io.dummie.v2.memory.CrystallizedSkill
	(AuthorityLevel)(0),            // 12: dummie.v2.AuthorityLevel
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
}
var file_proto_dummie_v2_memory_proto_depIdxs = []int32{
	5,  // 0: io.dummie.v2.memory.DecisionRecord.context:type_name -> io.dummie.v2.memory.SixDimensionalContext
	1,  // 1: io.dummie.v2.memory.SessionCrystallization.decisions:type_name -> io.dummie.v2.memory.DecisionRecord
	2,  // 2: io.dummie.v2.memory.SessionCrystallization.lessons:type_name -> io.dummie.v2.memory.Lesson
	3,  // 3: io.dummie.v2.memory.SessionCrystallization.ambiguities:type_name -> io.dummie.v2.memory.Ambiguity
	12, // 4: io.dummie.v2.memory.SixDimensionalContext.authority_a:type_name -> dummie.v2.AuthorityLevel
	0,  // 5: io.dummie.v2.memory.SixDimensionalContext.intent_i:type_name -> io.dummie.v2.memory.IntentType
	5,  // 6: io.dummie.v2.memory.MemoryNode4DTES.context:type_name -> io.dummie.v2.memory.SixDimensionalContext
	5,  // 7: io.dummie.v2.memory.EgoState.context:type_name -> io.dummie.v2.memory.SixDimensionalContext
	8,  // 8: io.dummie.v2.memory.OntologicalMap.layers:type_name -> io.dummie.v2.memory.LayerCertainty
	13, // 9: io.dummie.v2.memory.OntologicalMap.updated_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_dummie_v2_memory_proto_init() }
func file_proto_dummie_v2_memory_proto_init() {
	if File_proto_dummie_v2_memory_proto != nil {
		return
	}
	file_proto_dummie_v2_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dummie_v2_memory_proto_rawDesc), len(file_proto_dummie_v2_memory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dummie_v2_memory_proto_goTypes,
		DependencyIndexes: file_proto_dummie_v2_memory_proto_depIdxs,
		EnumInfos:         file_proto_dummie_v2_memory_proto_enumTypes,
		MessageInfos:      file_proto_dummie_v2_memory_proto_msgTypes,
	}.Build()
	File_proto_dummie_v2_memory_proto = out.File
	file_proto_dummie_v2_memory_proto_goTypes = nil
	file_proto_dummie_v2_memory_proto_depIdxs = nil
}
