# Spec Reference: 192_embedding_mesh_foundation
from pathlib import Path
from typing import Dict, List, Any
from .contracts import (
    StructuralClass,
    EvidenceType,
    Recommendation,
    RiskLevel,
    StructuralFinding
)
from .evidence import EvidenceCollector


class StructuralClassifier:
    def __init__(self, collector: EvidenceCollector):
        self.collector = collector

    def classify(self, file_rec: Dict[str, Any]) -> StructuralFinding:
        path = file_rec.get("path", "")
        current_class_str = file_rec.get("classification", "UNKNOWN").upper()
        
        # Parse current class
        try:
            current_class = StructuralClass(current_class_str)
        except ValueError:
            current_class = StructuralClass.UNKNOWN
            
        evidence = self.collector.collect_evidence(path)
        p = Path(path)
        
        # Invariants & variables to build structural finding
        proposed_class = StructuralClass.UNKNOWN
        risk = RiskLevel.LOW
        recommendation = Recommendation.NO_ACTION
        confidence = 1.0
        reasons: List[str] = []
        related_specs: List[str] = []
        related_tests: List[str] = []
        related_runtime: List[str] = []
        safe_to_change = True
        requires_human_review = False
        
        # 1. Config matching
        if EvidenceType.PACKAGE_MANIFEST in evidence or p.suffix in [".toml", ".lock", ".dockerfile", ".gitignore"] or p.name in ["mix.exs", "go.mod", "Makefile", "package.json"]:
            proposed_class = StructuralClass.CONFIG
            reasons.append("Configuration file or build system manifest detected.")
            recommendation = Recommendation.NO_ACTION
            
        # 2. Report matching
        elif path.startswith(".aiwg/reports/") or path.startswith(".aiwg/schemas/"):
            proposed_class = StructuralClass.REPORT
            reasons.append("Artifact report or schema generated by system.")
            recommendation = Recommendation.NO_ACTION
            
        # 3. Legacy matching
        elif EvidenceType.LEGACY_PATH in evidence:
            proposed_class = StructuralClass.LEGACY
            reasons.append("Resides in legacy, deprecated, or historical pathway.")
            risk = RiskLevel.LOW
            recommendation = Recommendation.MARK_LEGACY
            
        # 4. Generated matching
        elif EvidenceType.GENERATED_MARKER in evidence:
            proposed_class = StructuralClass.GENERATED
            reasons.append("Contains autogeneration tokens or matches protobuf serialization naming patterns.")
            recommendation = Recommendation.MARK_GENERATED
            risk = RiskLevel.LOW
            
        # 5. Experimental matching
        elif any(exp_token in path.lower() for exp_token in ["scratch", "experiment", "playground", "prototype", "mock", "demo"]):
            proposed_class = StructuralClass.EXPERIMENTAL
            reasons.append("Located in an experimental workspace, scratchpad, or playground directory.")
            recommendation = Recommendation.MARK_EXPERIMENTAL
            risk = RiskLevel.LOW
            
        # 6. Active Spec matching
        elif path.startswith("doc/specs/") and p.suffix in [".md", ".json", ".feature", ".rules.json"]:
            proposed_class = StructuralClass.ACTIVE_SPEC
            reasons.append("Physical specification file verified under doc/specs/.")
            recommendation = Recommendation.KEEP_AND_TEST
            
        # 7. Active Test / Orphan Test matching
        elif EvidenceType.TEST_NAMING_MATCH in evidence or p.suffix == ".exs" and p.name.endswith("_test.exs"):
            has_runtime_ref = EvidenceType.REFERENCES_RUNTIME in evidence or path in self.collector.test_references
            
            if has_runtime_ref:
                proposed_class = StructuralClass.ACTIVE_TEST
                reasons.append("Test file verified with matching active runtime references.")
                recommendation = Recommendation.KEEP_AND_TEST
                if EvidenceType.REFERENCES_RUNTIME in evidence:
                    related_runtime = evidence[EvidenceType.REFERENCES_RUNTIME]
            else:
                # Orphan Test Candidate
                proposed_class = StructuralClass.ORPHAN_TEST_CANDIDATE
                reasons.append("Test file exists but lacks active runtime component imports or references.")
                recommendation = Recommendation.MAP_TO_RUNTIME
                risk = RiskLevel.MEDIUM
                safe_to_change = False
                requires_human_review = True
                
        # 8. Active Runtime vs Shadow Candidate matching
        elif path.startswith("layers/") or path.startswith("src/"):
            # Check special rule: empty __init__.py packaging glue
            if p.name == "__init__.py":
                # Classify as active runtime with low risk
                proposed_class = StructuralClass.ACTIVE_RUNTIME
                reasons.append("Empty or structural package initialization file (__init__.py packaging glue).")
                recommendation = Recommendation.NO_ACTION
                risk = RiskLevel.LOW
            else:
                # Evaluate active connections
                has_spec = (EvidenceType.REFERENCED_BY_SPEC in evidence or 
                            EvidenceType.PHYSICAL_MAP_REFERENCE in evidence or 
                            EvidenceType.CORE_SPEC_REFERENCE in evidence)
                has_test = EvidenceType.REFERENCED_BY_TEST in evidence
                
                # Extract associations
                if EvidenceType.REFERENCED_BY_SPEC in evidence:
                    related_specs = evidence[EvidenceType.REFERENCED_BY_SPEC]
                if EvidenceType.REFERENCED_BY_TEST in evidence:
                    related_tests = evidence[EvidenceType.REFERENCED_BY_TEST]
                    
                if has_spec and has_test:
                    proposed_class = StructuralClass.ACTIVE_RUNTIME
                    reasons.append("Highly connected runtime module containing verified spec and test relationships.")
                    recommendation = Recommendation.KEEP_AND_TEST
                    risk = RiskLevel.LOW
                elif has_spec:
                    proposed_class = StructuralClass.ACTIVE_RUNTIME
                    reasons.append("Active runtime module containing spec mapping but lacks test verification coverage.")
                    recommendation = Recommendation.MAP_TO_TEST
                    risk = RiskLevel.MEDIUM
                elif has_test:
                    proposed_class = StructuralClass.ACTIVE_RUNTIME
                    reasons.append("Active runtime module containing test coverage but lacks spec contract documentation.")
                    recommendation = Recommendation.MAP_TO_SPEC
                    risk = RiskLevel.MEDIUM
                else:
                    # Shadow Candidate
                    proposed_class = StructuralClass.SHADOW_CANDIDATE
                    reasons.append("Orphan runtime candidate with zero test references and no contract specifications.")
                    recommendation = Recommendation.NEEDS_OWNER
                    risk = RiskLevel.HIGH
                    safe_to_change = False
                    requires_human_review = True
        
        else:
            # Catch-all
            proposed_class = StructuralClass.UNKNOWN
            reasons.append("Resides outside of core system verification boundaries with no evidence refs.")
            recommendation = Recommendation.NEEDS_IMPORT_CHECK
            risk = RiskLevel.LOW
            
        evidence_list: List[str] = []
        for ev_type, refs in evidence.items():
            for ref in refs:
                evidence_list.append(f"{ev_type.value}: {ref}")
                
        return StructuralFinding(
            path=path,
            current_class=current_class,
            proposed_class=proposed_class,
            risk=risk,
            recommendation=recommendation,
            confidence=confidence,
            evidence_refs=evidence_list,
            reasons=reasons,
            related_specs=related_specs,
            related_tests=related_tests,
            related_runtime=related_runtime,
            safe_to_change=safe_to_change,
            requires_human_review=requires_human_review
        )
