Feature: Memory Integration
  Scenario: Create a MemoryRef from a Learning Episode
    Given a LearningEpisode generated by a mission
    When I create a MemoryRef for the episode
    Then a deterministic content hash is generated
    And Performance Metric: latency < 100ms
    And the reference is marked as kuzu_ready