// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: skill.proto

package skill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TechnicalName string                 `protobuf:"bytes,2,opt,name=technical_name,json=technicalName,proto3" json:"technical_name,omitempty"`
	BackendServer string                 `protobuf:"bytes,3,opt,name=backend_server,json=backendServer,proto3" json:"backend_server,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	JsonSchema    string                 `protobuf:"bytes,5,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	Invariants    []string               `protobuf:"bytes,6,rep,name=invariants,proto3" json:"invariants,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Skill) GetTechnicalName() string {
	if x != nil {
		return x.TechnicalName
	}
	return ""
}

func (x *Skill) GetBackendServer() string {
	if x != nil {
		return x.BackendServer
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *Skill) GetInvariants() []string {
	if x != nil {
		return x.Invariants
	}
	return nil
}

func (x *Skill) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SkillRegistry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillRegistry) Reset() {
	*x = SkillRegistry{}
	mi := &file_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRegistry) ProtoMessage() {}

func (x *SkillRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillRegistry.ProtoReflect.Descriptor instead.
func (*SkillRegistry) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{1}
}

func (x *SkillRegistry) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

var File_skill_proto protoreflect.FileDescriptor

const file_skill_proto_rawDesc = "" +
	"\n" +
	"\vskill.proto\x12\x0edummie.v3.core\"\xc6\x02\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etechnical_name\x18\x02 \x01(\tR\rtechnicalName\x12%\n" +
	"\x0ebackend_server\x18\x03 \x01(\tR\rbackendServer\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vjson_schema\x18\x05 \x01(\tR\n" +
	"jsonSchema\x12\x1e\n" +
	"\n" +
	"invariants\x18\x06 \x03(\tR\n" +
	"invariants\x12?\n" +
	"\bmetadata\x18\a \x03(\v2#.dummie.v3.core.Skill.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\rSkillRegistry\x12-\n" +
	"\x06skills\x18\x01 \x03(\v2\x15.dummie.v3.core.SkillR\x06skillsB&Z$github.com/dummie-engine/proto/skillb\x06proto3"

var (
	file_skill_proto_rawDescOnce sync.Once
	file_skill_proto_rawDescData []byte
)

func file_skill_proto_rawDescGZIP() []byte {
	file_skill_proto_rawDescOnce.Do(func() {
		file_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)))
	})
	return file_skill_proto_rawDescData
}

var file_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_skill_proto_goTypes = []any{
	(*Skill)(nil),         // 0: dummie.v3.core.Skill
	(*SkillRegistry)(nil), // 1: dummie.v3.core.SkillRegistry
	nil,                   // 2: dummie.v3.core.Skill.MetadataEntry
}
var file_skill_proto_depIdxs = []int32{
	2, // 0: dummie.v3.core.Skill.metadata:type_name -> dummie.v3.core.Skill.MetadataEntry
	0, // 1: dummie.v3.core.SkillRegistry.skills:type_name -> dummie.v3.core.Skill
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_skill_proto_init() }
func file_skill_proto_init() {
	if File_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skill_proto_goTypes,
		DependencyIndexes: file_skill_proto_depIdxs,
		MessageInfos:      file_skill_proto_msgTypes,
	}.Build()
	File_skill_proto = out.File
	file_skill_proto_goTypes = nil
	file_skill_proto_depIdxs = nil
}
