Feature: Blindaje Legal y Cumplimiento - L-Shield (DE-V2-L3-24)
  Criterios de Aceptación Ejecutables para el Blindaje Legal.

  Scenario: Prevent GPL Contamination
    Given a new code block generated by an agent
    And the code has >80% structural similarity to an AGPL library
    When the Copyright Gavel (L4 Zig) scans the buffer
    Then it must inject a "LEGAL_VETO" into the NATS bus
    And the commit must be blocked
    And Performance Metric: license_scan_latency < 500ms

  Scenario: Audit Provenance of Inference (PoI)
    Given a new line of code in the monorepo
    When a security audit is conducted
    Then it must be possible to trace the "agent_id", "model_hash" and the "Architecture_Decision" linked to it
    And the data must match the "Event Store (Redb)" records
    And Performance Metric: provenance_lookup < 100ms
