// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/dummie/v2/orchestration.proto

package dummie_v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestrationService_ExecuteTask_FullMethodName   = "/dummie.v2.OrchestrationService/ExecuteTask"
	OrchestrationService_StreamThought_FullMethodName = "/dummie.v2.OrchestrationService/StreamThought"
	OrchestrationService_SubmitIntent_FullMethodName  = "/dummie.v2.OrchestrationService/SubmitIntent"
)

// OrchestrationServiceClient is the client API for OrchestrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrchestrationService: El Cerebro (Python) coordina tareas.
type OrchestrationServiceClient interface {
	ExecuteTask(ctx context.Context, in *AgentTask, opts ...grpc.CallOption) (*TaskResult, error)
	StreamThought(ctx context.Context, in *AgentIntent, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ThoughtTrace], error)
	SubmitIntent(ctx context.Context, in *AgentIntent, opts ...grpc.CallOption) (*TaskResult, error)
}

type orchestrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestrationServiceClient(cc grpc.ClientConnInterface) OrchestrationServiceClient {
	return &orchestrationServiceClient{cc}
}

func (c *orchestrationServiceClient) ExecuteTask(ctx context.Context, in *AgentTask, opts ...grpc.CallOption) (*TaskResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResult)
	err := c.cc.Invoke(ctx, OrchestrationService_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationServiceClient) StreamThought(ctx context.Context, in *AgentIntent, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ThoughtTrace], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestrationService_ServiceDesc.Streams[0], OrchestrationService_StreamThought_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentIntent, ThoughtTrace]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestrationService_StreamThoughtClient = grpc.ServerStreamingClient[ThoughtTrace]

func (c *orchestrationServiceClient) SubmitIntent(ctx context.Context, in *AgentIntent, opts ...grpc.CallOption) (*TaskResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResult)
	err := c.cc.Invoke(ctx, OrchestrationService_SubmitIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestrationServiceServer is the server API for OrchestrationService service.
// All implementations must embed UnimplementedOrchestrationServiceServer
// for forward compatibility.
//
// OrchestrationService: El Cerebro (Python) coordina tareas.
type OrchestrationServiceServer interface {
	ExecuteTask(context.Context, *AgentTask) (*TaskResult, error)
	StreamThought(*AgentIntent, grpc.ServerStreamingServer[ThoughtTrace]) error
	SubmitIntent(context.Context, *AgentIntent) (*TaskResult, error)
	mustEmbedUnimplementedOrchestrationServiceServer()
}

// UnimplementedOrchestrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestrationServiceServer struct{}

func (UnimplementedOrchestrationServiceServer) ExecuteTask(context.Context, *AgentTask) (*TaskResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedOrchestrationServiceServer) StreamThought(*AgentIntent, grpc.ServerStreamingServer[ThoughtTrace]) error {
	return status.Error(codes.Unimplemented, "method StreamThought not implemented")
}
func (UnimplementedOrchestrationServiceServer) SubmitIntent(context.Context, *AgentIntent) (*TaskResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitIntent not implemented")
}
func (UnimplementedOrchestrationServiceServer) mustEmbedUnimplementedOrchestrationServiceServer() {}
func (UnimplementedOrchestrationServiceServer) testEmbeddedByValue()                              {}

// UnsafeOrchestrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestrationServiceServer will
// result in compilation errors.
type UnsafeOrchestrationServiceServer interface {
	mustEmbedUnimplementedOrchestrationServiceServer()
}

func RegisterOrchestrationServiceServer(s grpc.ServiceRegistrar, srv OrchestrationServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestrationService_ServiceDesc, srv)
}

func _OrchestrationService_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServiceServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationService_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServiceServer).ExecuteTask(ctx, req.(*AgentTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationService_StreamThought_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgentIntent)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestrationServiceServer).StreamThought(m, &grpc.GenericServerStream[AgentIntent, ThoughtTrace]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestrationService_StreamThoughtServer = grpc.ServerStreamingServer[ThoughtTrace]

func _OrchestrationService_SubmitIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServiceServer).SubmitIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationService_SubmitIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServiceServer).SubmitIntent(ctx, req.(*AgentIntent))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestrationService_ServiceDesc is the grpc.ServiceDesc for OrchestrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dummie.v2.OrchestrationService",
	HandlerType: (*OrchestrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTask",
			Handler:    _OrchestrationService_ExecuteTask_Handler,
		},
		{
			MethodName: "SubmitIntent",
			Handler:    _OrchestrationService_SubmitIntent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamThought",
			Handler:       _OrchestrationService_StreamThought_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/dummie/v2/orchestration.proto",
}

const (
	SandboxExecutionService_RunCode_FullMethodName      = "/dummie.v2.SandboxExecutionService/RunCode"
	SandboxExecutionService_InstallSkill_FullMethodName = "/dummie.v2.SandboxExecutionService/InstallSkill"
)

// SandboxExecutionServiceClient is the client API for SandboxExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxExecutionService: El Escudo (Rust) ejecuta código aislado.
type SandboxExecutionServiceClient interface {
	RunCode(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	InstallSkill(ctx context.Context, in *SkillData, opts ...grpc.CallOption) (*TaskResult, error)
}

type sandboxExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxExecutionServiceClient(cc grpc.ClientConnInterface) SandboxExecutionServiceClient {
	return &sandboxExecutionServiceClient{cc}
}

func (c *sandboxExecutionServiceClient) RunCode(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, SandboxExecutionService_RunCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxExecutionServiceClient) InstallSkill(ctx context.Context, in *SkillData, opts ...grpc.CallOption) (*TaskResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResult)
	err := c.cc.Invoke(ctx, SandboxExecutionService_InstallSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxExecutionServiceServer is the server API for SandboxExecutionService service.
// All implementations must embed UnimplementedSandboxExecutionServiceServer
// for forward compatibility.
//
// SandboxExecutionService: El Escudo (Rust) ejecuta código aislado.
type SandboxExecutionServiceServer interface {
	RunCode(context.Context, *ExecutionRequest) (*ExecutionResponse, error)
	InstallSkill(context.Context, *SkillData) (*TaskResult, error)
	mustEmbedUnimplementedSandboxExecutionServiceServer()
}

// UnimplementedSandboxExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxExecutionServiceServer struct{}

func (UnimplementedSandboxExecutionServiceServer) RunCode(context.Context, *ExecutionRequest) (*ExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCode not implemented")
}
func (UnimplementedSandboxExecutionServiceServer) InstallSkill(context.Context, *SkillData) (*TaskResult, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallSkill not implemented")
}
func (UnimplementedSandboxExecutionServiceServer) mustEmbedUnimplementedSandboxExecutionServiceServer() {
}
func (UnimplementedSandboxExecutionServiceServer) testEmbeddedByValue() {}

// UnsafeSandboxExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxExecutionServiceServer will
// result in compilation errors.
type UnsafeSandboxExecutionServiceServer interface {
	mustEmbedUnimplementedSandboxExecutionServiceServer()
}

func RegisterSandboxExecutionServiceServer(s grpc.ServiceRegistrar, srv SandboxExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxExecutionService_ServiceDesc, srv)
}

func _SandboxExecutionService_RunCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxExecutionServiceServer).RunCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxExecutionService_RunCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxExecutionServiceServer).RunCode(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxExecutionService_InstallSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxExecutionServiceServer).InstallSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxExecutionService_InstallSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxExecutionServiceServer).InstallSkill(ctx, req.(*SkillData))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxExecutionService_ServiceDesc is the grpc.ServiceDesc for SandboxExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dummie.v2.SandboxExecutionService",
	HandlerType: (*SandboxExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunCode",
			Handler:    _SandboxExecutionService_RunCode_Handler,
		},
		{
			MethodName: "InstallSkill",
			Handler:    _SandboxExecutionService_InstallSkill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dummie/v2/orchestration.proto",
}

const (
	TimeKeeperService_GetVectorClock_FullMethodName = "/dummie.v2.TimeKeeperService/GetVectorClock"
	TimeKeeperService_RegisterEvent_FullMethodName  = "/dummie.v2.TimeKeeperService/RegisterEvent"
	TimeKeeperService_TruncateKV_FullMethodName     = "/dummie.v2.TimeKeeperService/TruncateKV"
)

// TimeKeeperServiceClient is the client API for TimeKeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TimeKeeperService: El Relojero (Go) mantiene el DAG causal.
type TimeKeeperServiceClient interface {
	GetVectorClock(ctx context.Context, in *VectorClockRequest, opts ...grpc.CallOption) (*VectorClockResponse, error)
	RegisterEvent(ctx context.Context, in *EventId, opts ...grpc.CallOption) (*TaskResult, error)
	TruncateKV(ctx context.Context, in *EventId, opts ...grpc.CallOption) (*TaskResult, error)
}

type timeKeeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeKeeperServiceClient(cc grpc.ClientConnInterface) TimeKeeperServiceClient {
	return &timeKeeperServiceClient{cc}
}

func (c *timeKeeperServiceClient) GetVectorClock(ctx context.Context, in *VectorClockRequest, opts ...grpc.CallOption) (*VectorClockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorClockResponse)
	err := c.cc.Invoke(ctx, TimeKeeperService_GetVectorClock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeKeeperServiceClient) RegisterEvent(ctx context.Context, in *EventId, opts ...grpc.CallOption) (*TaskResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResult)
	err := c.cc.Invoke(ctx, TimeKeeperService_RegisterEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeKeeperServiceClient) TruncateKV(ctx context.Context, in *EventId, opts ...grpc.CallOption) (*TaskResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResult)
	err := c.cc.Invoke(ctx, TimeKeeperService_TruncateKV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeKeeperServiceServer is the server API for TimeKeeperService service.
// All implementations must embed UnimplementedTimeKeeperServiceServer
// for forward compatibility.
//
// TimeKeeperService: El Relojero (Go) mantiene el DAG causal.
type TimeKeeperServiceServer interface {
	GetVectorClock(context.Context, *VectorClockRequest) (*VectorClockResponse, error)
	RegisterEvent(context.Context, *EventId) (*TaskResult, error)
	TruncateKV(context.Context, *EventId) (*TaskResult, error)
	mustEmbedUnimplementedTimeKeeperServiceServer()
}

// UnimplementedTimeKeeperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimeKeeperServiceServer struct{}

func (UnimplementedTimeKeeperServiceServer) GetVectorClock(context.Context, *VectorClockRequest) (*VectorClockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVectorClock not implemented")
}
func (UnimplementedTimeKeeperServiceServer) RegisterEvent(context.Context, *EventId) (*TaskResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEvent not implemented")
}
func (UnimplementedTimeKeeperServiceServer) TruncateKV(context.Context, *EventId) (*TaskResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TruncateKV not implemented")
}
func (UnimplementedTimeKeeperServiceServer) mustEmbedUnimplementedTimeKeeperServiceServer() {}
func (UnimplementedTimeKeeperServiceServer) testEmbeddedByValue()                           {}

// UnsafeTimeKeeperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeKeeperServiceServer will
// result in compilation errors.
type UnsafeTimeKeeperServiceServer interface {
	mustEmbedUnimplementedTimeKeeperServiceServer()
}

func RegisterTimeKeeperServiceServer(s grpc.ServiceRegistrar, srv TimeKeeperServiceServer) {
	// If the following call panics, it indicates UnimplementedTimeKeeperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimeKeeperService_ServiceDesc, srv)
}

func _TimeKeeperService_GetVectorClock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeKeeperServiceServer).GetVectorClock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeKeeperService_GetVectorClock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeKeeperServiceServer).GetVectorClock(ctx, req.(*VectorClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeKeeperService_RegisterEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeKeeperServiceServer).RegisterEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeKeeperService_RegisterEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeKeeperServiceServer).RegisterEvent(ctx, req.(*EventId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeKeeperService_TruncateKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeKeeperServiceServer).TruncateKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeKeeperService_TruncateKV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeKeeperServiceServer).TruncateKV(ctx, req.(*EventId))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeKeeperService_ServiceDesc is the grpc.ServiceDesc for TimeKeeperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeKeeperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dummie.v2.TimeKeeperService",
	HandlerType: (*TimeKeeperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVectorClock",
			Handler:    _TimeKeeperService_GetVectorClock_Handler,
		},
		{
			MethodName: "RegisterEvent",
			Handler:    _TimeKeeperService_RegisterEvent_Handler,
		},
		{
			MethodName: "TruncateKV",
			Handler:    _TimeKeeperService_TruncateKV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dummie/v2/orchestration.proto",
}

const (
	ArchitecturalValidationService_ValidateConformity_FullMethodName   = "/dummie.v2.ArchitecturalValidationService/ValidateConformity"
	ArchitecturalValidationService_CheckAtomicIsolation_FullMethodName = "/dummie.v2.ArchitecturalValidationService/CheckAtomicIsolation"
)

// ArchitecturalValidationServiceClient is the client API for ArchitecturalValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArchitecturalValidationService: El Validador (Rust/L3) asegura conformidad Hexagonal.
type ArchitecturalValidationServiceClient interface {
	ValidateConformity(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error)
	CheckAtomicIsolation(ctx context.Context, in *NodeIdentity, opts ...grpc.CallOption) (*TaskResult, error)
}

type architecturalValidationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArchitecturalValidationServiceClient(cc grpc.ClientConnInterface) ArchitecturalValidationServiceClient {
	return &architecturalValidationServiceClient{cc}
}

func (c *architecturalValidationServiceClient) ValidateConformity(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, ArchitecturalValidationService_ValidateConformity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *architecturalValidationServiceClient) CheckAtomicIsolation(ctx context.Context, in *NodeIdentity, opts ...grpc.CallOption) (*TaskResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResult)
	err := c.cc.Invoke(ctx, ArchitecturalValidationService_CheckAtomicIsolation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArchitecturalValidationServiceServer is the server API for ArchitecturalValidationService service.
// All implementations must embed UnimplementedArchitecturalValidationServiceServer
// for forward compatibility.
//
// ArchitecturalValidationService: El Validador (Rust/L3) asegura conformidad Hexagonal.
type ArchitecturalValidationServiceServer interface {
	ValidateConformity(context.Context, *ValidationRequest) (*ValidationResponse, error)
	CheckAtomicIsolation(context.Context, *NodeIdentity) (*TaskResult, error)
	mustEmbedUnimplementedArchitecturalValidationServiceServer()
}

// UnimplementedArchitecturalValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArchitecturalValidationServiceServer struct{}

func (UnimplementedArchitecturalValidationServiceServer) ValidateConformity(context.Context, *ValidationRequest) (*ValidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConformity not implemented")
}
func (UnimplementedArchitecturalValidationServiceServer) CheckAtomicIsolation(context.Context, *NodeIdentity) (*TaskResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAtomicIsolation not implemented")
}
func (UnimplementedArchitecturalValidationServiceServer) mustEmbedUnimplementedArchitecturalValidationServiceServer() {
}
func (UnimplementedArchitecturalValidationServiceServer) testEmbeddedByValue() {}

// UnsafeArchitecturalValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArchitecturalValidationServiceServer will
// result in compilation errors.
type UnsafeArchitecturalValidationServiceServer interface {
	mustEmbedUnimplementedArchitecturalValidationServiceServer()
}

func RegisterArchitecturalValidationServiceServer(s grpc.ServiceRegistrar, srv ArchitecturalValidationServiceServer) {
	// If the following call panics, it indicates UnimplementedArchitecturalValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArchitecturalValidationService_ServiceDesc, srv)
}

func _ArchitecturalValidationService_ValidateConformity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchitecturalValidationServiceServer).ValidateConformity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchitecturalValidationService_ValidateConformity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchitecturalValidationServiceServer).ValidateConformity(ctx, req.(*ValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchitecturalValidationService_CheckAtomicIsolation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchitecturalValidationServiceServer).CheckAtomicIsolation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchitecturalValidationService_CheckAtomicIsolation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchitecturalValidationServiceServer).CheckAtomicIsolation(ctx, req.(*NodeIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

// ArchitecturalValidationService_ServiceDesc is the grpc.ServiceDesc for ArchitecturalValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArchitecturalValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dummie.v2.ArchitecturalValidationService",
	HandlerType: (*ArchitecturalValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateConformity",
			Handler:    _ArchitecturalValidationService_ValidateConformity_Handler,
		},
		{
			MethodName: "CheckAtomicIsolation",
			Handler:    _ArchitecturalValidationService_CheckAtomicIsolation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dummie/v2/orchestration.proto",
}
