# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.dummie.v2 import core_pb2 as proto_dot_dummie_dot_v2_dot_core__pb2
from proto.dummie.v2 import orchestration_pb2 as proto_dot_dummie_dot_v2_dot_orchestration__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/dummie/v2/orchestration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestrationServiceStub(object):
    """=== Servicios Centrales ===

    OrchestrationService: El Cerebro (Python) coordina tareas.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/dummie.v2.OrchestrationService/ExecuteTask',
                request_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.AgentTask.SerializeToString,
                response_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
                _registered_method=True)
        self.StreamThought = channel.unary_stream(
                '/dummie.v2.OrchestrationService/StreamThought',
                request_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.AgentIntent.SerializeToString,
                response_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.ThoughtTrace.FromString,
                _registered_method=True)
        self.SubmitIntent = channel.unary_unary(
                '/dummie.v2.OrchestrationService/SubmitIntent',
                request_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.AgentIntent.SerializeToString,
                response_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
                _registered_method=True)


class OrchestrationServiceServicer(object):
    """=== Servicios Centrales ===

    OrchestrationService: El Cerebro (Python) coordina tareas.
    """

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamThought(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.AgentTask.FromString,
                    response_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.SerializeToString,
            ),
            'StreamThought': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamThought,
                    request_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.AgentIntent.FromString,
                    response_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.ThoughtTrace.SerializeToString,
            ),
            'SubmitIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitIntent,
                    request_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.AgentIntent.FromString,
                    response_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dummie.v2.OrchestrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dummie.v2.OrchestrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestrationService(object):
    """=== Servicios Centrales ===

    OrchestrationService: El Cerebro (Python) coordina tareas.
    """

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummie.v2.OrchestrationService/ExecuteTask',
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.AgentTask.SerializeToString,
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamThought(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dummie.v2.OrchestrationService/StreamThought',
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.AgentIntent.SerializeToString,
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.ThoughtTrace.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummie.v2.OrchestrationService/SubmitIntent',
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.AgentIntent.SerializeToString,
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SandboxExecutionServiceStub(object):
    """SandboxExecutionService: El Escudo (Rust) ejecuta código aislado.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunCode = channel.unary_unary(
                '/dummie.v2.SandboxExecutionService/RunCode',
                request_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.ExecutionRequest.SerializeToString,
                response_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.ExecutionResponse.FromString,
                _registered_method=True)
        self.InstallSkill = channel.unary_unary(
                '/dummie.v2.SandboxExecutionService/InstallSkill',
                request_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.SkillData.SerializeToString,
                response_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
                _registered_method=True)


class SandboxExecutionServiceServicer(object):
    """SandboxExecutionService: El Escudo (Rust) ejecuta código aislado.
    """

    def RunCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallSkill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunCode': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCode,
                    request_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.ExecutionRequest.FromString,
                    response_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.ExecutionResponse.SerializeToString,
            ),
            'InstallSkill': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallSkill,
                    request_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.SkillData.FromString,
                    response_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dummie.v2.SandboxExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dummie.v2.SandboxExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxExecutionService(object):
    """SandboxExecutionService: El Escudo (Rust) ejecuta código aislado.
    """

    @staticmethod
    def RunCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummie.v2.SandboxExecutionService/RunCode',
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.ExecutionRequest.SerializeToString,
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.ExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallSkill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummie.v2.SandboxExecutionService/InstallSkill',
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.SkillData.SerializeToString,
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TimeKeeperServiceStub(object):
    """TimeKeeperService: El Relojero (Go) mantiene el DAG causal.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVectorClock = channel.unary_unary(
                '/dummie.v2.TimeKeeperService/GetVectorClock',
                request_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.VectorClockRequest.SerializeToString,
                response_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.VectorClockResponse.FromString,
                _registered_method=True)
        self.RegisterEvent = channel.unary_unary(
                '/dummie.v2.TimeKeeperService/RegisterEvent',
                request_serializer=proto_dot_dummie_dot_v2_dot_core__pb2.EventId.SerializeToString,
                response_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
                _registered_method=True)
        self.TruncateKV = channel.unary_unary(
                '/dummie.v2.TimeKeeperService/TruncateKV',
                request_serializer=proto_dot_dummie_dot_v2_dot_core__pb2.EventId.SerializeToString,
                response_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
                _registered_method=True)


class TimeKeeperServiceServicer(object):
    """TimeKeeperService: El Relojero (Go) mantiene el DAG causal.
    """

    def GetVectorClock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TruncateKV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeKeeperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVectorClock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVectorClock,
                    request_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.VectorClockRequest.FromString,
                    response_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.VectorClockResponse.SerializeToString,
            ),
            'RegisterEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEvent,
                    request_deserializer=proto_dot_dummie_dot_v2_dot_core__pb2.EventId.FromString,
                    response_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.SerializeToString,
            ),
            'TruncateKV': grpc.unary_unary_rpc_method_handler(
                    servicer.TruncateKV,
                    request_deserializer=proto_dot_dummie_dot_v2_dot_core__pb2.EventId.FromString,
                    response_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dummie.v2.TimeKeeperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dummie.v2.TimeKeeperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TimeKeeperService(object):
    """TimeKeeperService: El Relojero (Go) mantiene el DAG causal.
    """

    @staticmethod
    def GetVectorClock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummie.v2.TimeKeeperService/GetVectorClock',
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.VectorClockRequest.SerializeToString,
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.VectorClockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummie.v2.TimeKeeperService/RegisterEvent',
            proto_dot_dummie_dot_v2_dot_core__pb2.EventId.SerializeToString,
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TruncateKV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummie.v2.TimeKeeperService/TruncateKV',
            proto_dot_dummie_dot_v2_dot_core__pb2.EventId.SerializeToString,
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ArchitecturalValidationServiceStub(object):
    """ArchitecturalValidationService: El Validador (Rust/L3) asegura conformidad Hexagonal.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateConformity = channel.unary_unary(
                '/dummie.v2.ArchitecturalValidationService/ValidateConformity',
                request_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.ValidationRequest.SerializeToString,
                response_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.ValidationResponse.FromString,
                _registered_method=True)
        self.CheckAtomicIsolation = channel.unary_unary(
                '/dummie.v2.ArchitecturalValidationService/CheckAtomicIsolation',
                request_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.NodeIdentity.SerializeToString,
                response_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
                _registered_method=True)


class ArchitecturalValidationServiceServicer(object):
    """ArchitecturalValidationService: El Validador (Rust/L3) asegura conformidad Hexagonal.
    """

    def ValidateConformity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAtomicIsolation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArchitecturalValidationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateConformity': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateConformity,
                    request_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.ValidationRequest.FromString,
                    response_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.ValidationResponse.SerializeToString,
            ),
            'CheckAtomicIsolation': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAtomicIsolation,
                    request_deserializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.NodeIdentity.FromString,
                    response_serializer=proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dummie.v2.ArchitecturalValidationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dummie.v2.ArchitecturalValidationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArchitecturalValidationService(object):
    """ArchitecturalValidationService: El Validador (Rust/L3) asegura conformidad Hexagonal.
    """

    @staticmethod
    def ValidateConformity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummie.v2.ArchitecturalValidationService/ValidateConformity',
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.ValidationRequest.SerializeToString,
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.ValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAtomicIsolation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummie.v2.ArchitecturalValidationService/CheckAtomicIsolation',
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.NodeIdentity.SerializeToString,
            proto_dot_dummie_dot_v2_dot_orchestration__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
