# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sdk_core_api_pb2 as sdk__core__api__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sdk_core_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DummieOrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteIntent = channel.unary_unary(
                '/dummie.v1.DummieOrchestrator/ExecuteIntent',
                request_serializer=sdk__core__api__pb2.IntentRequest.SerializeToString,
                response_deserializer=sdk__core__api__pb2.IntentResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/dummie.v1.DummieOrchestrator/StreamEvents',
                request_serializer=sdk__core__api__pb2.SessionRequest.SerializeToString,
                response_deserializer=sdk__core__api__pb2.AgentEvent.FromString,
                _registered_method=True)


class DummieOrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DummieOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteIntent,
                    request_deserializer=sdk__core__api__pb2.IntentRequest.FromString,
                    response_serializer=sdk__core__api__pb2.IntentResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=sdk__core__api__pb2.SessionRequest.FromString,
                    response_serializer=sdk__core__api__pb2.AgentEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dummie.v1.DummieOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dummie.v1.DummieOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DummieOrchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummie.v1.DummieOrchestrator/ExecuteIntent',
            sdk__core__api__pb2.IntentRequest.SerializeToString,
            sdk__core__api__pb2.IntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dummie.v1.DummieOrchestrator/StreamEvents',
            sdk__core__api__pb2.SessionRequest.SerializeToString,
            sdk__core__api__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
