# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sdk_core_api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sdk_core_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sdk_core_api.proto\x12\tdummie.v1\"1\n\rIntentRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04goal\x18\x02 \x01(\t\"8\n\x0eIntentResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"$\n\x0eSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"D\n\nAgentEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t2\x9e\x01\n\x12\x44ummieOrchestrator\x12\x44\n\rExecuteIntent\x12\x18.dummie.v1.IntentRequest\x1a\x19.dummie.v1.IntentResponse\x12\x42\n\x0cStreamEvents\x12\x19.dummie.v1.SessionRequest\x1a\x15.dummie.v1.AgentEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdk_core_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTENTREQUEST']._serialized_start=33
  _globals['_INTENTREQUEST']._serialized_end=82
  _globals['_INTENTRESPONSE']._serialized_start=84
  _globals['_INTENTRESPONSE']._serialized_end=140
  _globals['_SESSIONREQUEST']._serialized_start=142
  _globals['_SESSIONREQUEST']._serialized_end=178
  _globals['_AGENTEVENT']._serialized_start=180
  _globals['_AGENTEVENT']._serialized_end=248
  _globals['_DUMMIEORCHESTRATOR']._serialized_start=251
  _globals['_DUMMIEORCHESTRATOR']._serialized_end=409
# @@protoc_insertion_point(module_scope)
